@startuml

!include _sequence_config.puml.incl

participant "$str_somds_consumer" as consumer
participant "$str_somds_provider" as provider

== SDPi [DEV-23] Announce Network Presence  ==
|||
group unsecured
    provider -> consumer: BICEPS: Hello(Provider UID, Discovery Scope, ...)
end
|||

@enduml