= Volume 0 -- IHE Technical Frameworks General Introduction

NOTE:  This document integrates all the content that makes up the supplement volume 0 (IHE General Introduction) document.

OTE:  This document integrates all the content that makes up the supplement volume 0 document.

IMPORTANT:  Migrate the content below from main.adoc into this document OR rename main.adoc to this ... though the content is different.  +
{empty} +
*_See the Word document for what this is supposed to look like_*.


[#vol0_clause_general,sdpi_offset=clear]
== IHE Technical Frameworks General Introduction
The http://ihe.net/Technical_Frameworks/#GenIntro[IHE Technical Framework General Introduction] is shared by all of the IHE domain technical frameworks. Each technical framework volume contains links to this document where appropriate.

include::tf0-ch-9-copyrights.adoc[]

// 10 Trademark

[sdpi_offset=10]
== Trademark
NOTE:  TBD if there are any additional trademark clauses for this section; for example "SDC" ???


[sdpi_offset=1]
[sdpi_offset=clear]
== IHE Technical Frameworks General Introduction Appendices
The http://ihe.net/Technical_Frameworks/#GenIntro[IHE Technical Framework General Introduction Appendices] are components shared by all of the IHE domain technical frameworks. Each technical framework volume contains links to these documents where appropriate.

include::tf0-ch-a-actors.adoc[]

include::tf0-ch-b-transactions.adoc[]

include::tf0-ch-d-glossary.adoc[]

