@startuml

!include ../_sequence_config.puml.incl

sdc_sc -> sdc_sp: Subscribe({\n    DescriptionModificationReport, \n    EpisodicMetricReport, EpisodicContextReport, EpisodicComponentReport, \n    WaveformStream\n})
sdc_sc <-- sdc_sp: SubscribeResponse(SubscriptionManager, ExpirationTime)

loop while subscription is running and reports ensue
    opt
        sdc_sc <- sdc_sp: Notification(DescriptionModificationReport)
        note left: Description modifications\nalways first
    end

    group one or more of
        sdc_sc <- sdc_sp: Notification(EpisodicMetricReport)
        sdc_sc <- sdc_sp: Notification(EpisodicContextReport)
        sdc_sc <- sdc_sp: Notification(EpisodicComponentReport)
        sdc_sc <- sdc_sp: Notification(WaveformStream)
    end
end

!include ../update_report_retrieval/update_report_retrieval__unsubscribe.puml.incl

@enduml