==== Connection Time Delay

When a <<actor_somds_provider>> joins a network and sends out a <<vol2_clause_dev_23_message_hello, {var_uri_ws_discovery_hello}>> message, depending on the number of <<actor_somds_consumer>>s that are interested in the data of that <<actor_somds_provider>>, the <<actor_somds_provider>> can get overwhelmed by incoming TCP connection requests and TLS handshakes. <<actor_somds_provider>>s and <<actor_somds_consumer>>s can implement different actions in order to avoid flooding of TCP connection requests and TLS handshakes under normal operating conditions. Each action comes with individual advantages and disadvantages.

===== Provider-controlled Delay

<<ieee_11073_20701_2018>> normatively references <<dpws_2009>> which in turn leverages <<ws_discovery_2009>> to provide distributed (ad-hoc) or centralized (managed) service registries. WS-Discovery decomposes into two message sequences, <<vol2_clause_appendix_mdpws_dev_23, implicit discovery>> and <<vol2_clause_appendix_mdpws_dev_24, explicit discovery>> of which implicit discovery can lead to loss of performance for <<actor_somds_provider>>s when multiple <<actor_somds_consumer>>s attempt to connect at the same time.


In order to suppress concurrent connection attempts, in the ad-hoc mode a <<actor_somds_provider>> can omit the <<property_transport_address>> from the {var_label_dev_23_message_hello} message. Subsequently, a <<actor_somds_consumer>> needs to send a {var_label_dev_24_message_resolve} message to resolve the <<actor_somds_provider>>'s <<property_transport_address>>.

.R0001
[sdpi_requirement,sdpi_req_id=1]
****
A <<actor_somds_provider>> may delay the Resolve Match response to a Resolve message.

NOTE: It is up to the MANUFACTURER to choose a delay that fits the hardware capabilities of their SDC SERVICE PROVIDER for concurrent connection requests.
****

===== Consumer-controlled Delay

Prioritization of connection establishment