
:var_transaction_id: DEV-23

:var_label_dev_23_message_hello: Hello
:var_label_dev_23_payload_provider_uid: Provider UID
:val_label_dev_23_payload_discovery_scope: Discovery Scope

//reset|+1|off
[#vol2_clause_dev_23,sdpi_offset=23]
=== Announce Network Presence [{var_transaction_id}]

==== Scope

[sdpi_transaction#transaction_dev_23,actors='actor_somds_provider actor_somds_consumer',figure=vol2_figure_dev_23_sequence,messages='message_announce_network_presence']

##NOTE THAT THE FIRST SENTENCE SHOULD BE THE SUMMARY THAT IS PUBLISHED IN THE TF-0 APPENDIX B TRANSACTIONS TABLE - but substituting with first sentence and not reftext ... HOW???
##
[[transaction_summary_dev_23,DEV-23 Announce Network Presence]]
This transaction is used to notify all <<actor_somds_consumer>>s that a <<actor_somds_provider>> is connected to the network and ready to exchange messages with other <<actor_somds_participant>>s.

==== Actor Roles

.Actor Roles {var_transaction_id}
[cols="1,2"]
|===
|Actor |Roles

|<<actor_somds_provider>>
|Announces its presence by broadcasting <<vol2_clause_dev_23_message_announce_network_presence>> messages to all listening systems.

|<<actor_somds_consumer>>
|Listens for <<vol2_clause_dev_23_message_announce_network_presence>> messages to identify any <<actor_somds_provider>>s that it may exchange messages with and further retrieve a <<actor_somds_provider>>'s service capabilities.

|===

==== Referenced Standards

* <<ieee_11073_10207_2017>> Section 9.2 Implicit Discovery

==== Messages

.Message Interaction Diagram {var_transaction_id}
[plantuml#vol2_figure_dev_23_sequence, target=puml-dev-23-sequence, format=svg, reftext='{figure-caption} {counter:refnum}',width=100%]
....
include::../../plantuml/vol2-figure-dev-23-sequence.puml[]
....

[#vol2_clause_dev_23_message_announce_network_presence]
===== {var_label_dev_23_message_hello}

The {var_label_dev_23_message_hello} message is part of the BICEPS _implicit discovery_ protocol for allowing <<actor_somds_consumer>>s to receive a notification when a <<actor_somds_provider>> is ready to exchange messages with other <<actor_somds_consumer>>s.

The {var_label_dev_23_message_hello} is a broadcast message that is sent from each <<actor_somds_provider>> to all listening <<actor_somds_consumer>>s (zero to many). Limited but sufficient information is provided with the message to enable <<actor_somds_consumer>>s to determine if they are interested in connecting with the <<actor_somds_provider>> discovering additional information.

[#vol2_clause_dev_23_message_announce_network_presence_trigger_events]
====== Trigger Events

This message is sent

1. whenever a <<actor_somds_provider>> joins a network,
2. when it is returning to normal _on-line_ operation after having indicated temporary suspension of message exchanges, or
3. when any metadata of the <<actor_somds_provider>> changes, e.g. when <<payload_dev_23_discovery_scope>> is updated.

[#vol2_clause_dev_23_message_announce_network_presence_message_semantics,sdpi_depth=+1]
====== Message Semantics

[[payload_dev_23_provider_uid]]Provider UID:: The <<property_somds_provider_uid>>.
[[payload_dev_23_discovery_scope]]Discovery Scope:: The <<property_discovery_scope>> of the <<actor_somds_provider>>.

[#vol2_clause_dev_23_message_announce_network_presence_expected_actions]
====== Expected Actions

When a <<actor_somds_provider>> sends this message, there is no expected or required responses. This is due to the fact that either there are no <<actor_somds_consumer>>s listening for announcement messages, or the information in the message (e.g., Discovery Type) is not of interest to any receiving <<actor_somds_consumer>>s.