@startuml SDPi DEV TF-1

!include _sequence_config.incl

title IHE Devices TF-1 SDPi Profile Transactions\n\n


== SDPi-P (Plug-and-trust) ==
    
    !include SDPi-P_Transactions/SDPi-P__main.puml
   
== SDPi-R (Reporting) ==

    !include SDPi-R_Transactions/SDPi-R__main.puml

== SDPi-A (Alerting) ==

    !include SDPi-A_Transactions/SDPi-A__main.puml

== SDPi-xC (external Control) ==

    !include SDPi-xC_Transactions/SDPi-xC__main.puml

@enduml