==== SDC/BICEPS semantic content

NOTE:  This file contains the content that profiles BICEPS semantics for use in the SDPi profiles.  It is a compliment to the other general requirements that are in chapter 8.2.

// 8.2.8
[sdpi_offset=8]
==== SDC/BICEPS semantic content

// 8.2.8.1
===== SDC/BICEPS Content Module

// 8.2.8.2
===== SDC/BICEPS Descriptive Model

// 8.2.8.3
===== SDC/BICEPS Relationship to Classic DIM

// 8.2.8.4
===== Nomenclature Considerations – Private Extensions & External Systems

// 8.2.8.5
===== Safety, Effectiveness, Security Content Requirements & Considerations

// 8.2.8.6
===== SDC/BICEPS Conventions for device specialization content modules

===== BICEPS Extension Provisions

====== Coded Attribute

BICEPS does not provide means to generically add attributes from the first partition of the IEEE 11073-10101 nomenclature to the MDIB. This becomes challenging if there are attributes required by <<actor_somds_provider>>s to provide information that is not covered by the BICEPS participant model.

For example, BICEPS does only support the following MDS meta information below the `pm:Mds/pm:MetaData` element:

* UDI
* Lot number
* Manufacturer name
* Expiration date
* Model name
* Model number
* Serial number

Some statically configured meta information like firmware versions or software versions can be added by means of production specification elements. Unfortunately, attributes like equipment labels do not exist and cannot be conveyed by using production specifications.

The SDPi profile specifies the _CodedAttribute_ extension that allows for a <<actor_somds_provider>> to provide attributes from the first partition of the IEEE 11073-10101 nomenclature for which there is no information item specified in the BICEPS participant model.

[sdpi_level=+1]
====== Model

The CodedAttribute XML Schema is available in

.MDS with CodedAttribute representing a Soft ID
====
[source,xml]
----
include::../listings/vol3-clause-biceps-content-example-equipment-label.xml[]
----
====

[sdpi_level=+1]
====== Requirements

.R0005
[sdpi_requirement#r0005,sdpi_req_level=shall]
****
A <<actor_somds_provider>> shall set `sdpi:MdcAttribute/@Code` to any code from the first partition of the IEEE 11073-10101 nomenclature in the range of 67841 (1::2305) to 68609 (1::3073).

.Notes
[%collapsible]
====
NOTE: This prevents manufacturers from using codes outside the intended range of attributes.
====
****



