// = Service-oriented Device Point-of-care Interoperability - Reporting (SDPi-R) Profile

// 11.
[#vol1_clause_sdpi_r_profile,sdpi_offset=11]
== Service-oriented Device Point-of-care Interoperability - Reporting (SDPi-R) Profile

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *SDPi Supplement Version Note*:  For SDPi 1.0 DEV Internal Review Version, this profile section remains fairly incomplete, with significant content needing to be migrated from the Word version of the supplement and then integrated into this AsciiDoc specification.
This will be completed in early January and *_an updated DEV Internal Review Version published by mid-January_*.

Note that the related transactions are completely defined in <<vol2_clause_transactions>>, and the <<actor_somds_dec_gateway>> is fully specified in <<#vol2_clause_appendix_sdpi_dec_gateway>>.
|===


The SDPi-Reporting ([[acronym_sdpi_r,SDPi-R]] SDPi-R) profile supports #TODO: add general description ...#

// 11.1
=== SDPi-R Actors, Transactions, and Content Modules

This section defines the actors, transactions, and/or content modules in this profile.
General definitions of actors are given in the https://profiles.ihe.net/GeneralIntro/ch-A.html[_Technical Frameworks General Introduction Appendix A_].
IHE Transactions can be found in the https://profiles.ihe.net/GeneralIntro/ch-B.html[_Technical Frameworks General Introduction Appendix B_].
Both appendices are located at https://profiles.ihe.net/GeneralIntro/[_profiles.ihe.net/GeneralIntro_].

<<vol1_figure_sdpi_r_actor_diagram>> shows the actors directly involved in the SDPi-R Profile.
The relevant transactions between them are detailed in the subsequent <<vol1_table_sdpi_r_actors_transactions>>.
Actor groupings, including abstract with concrete are detailed in <<vol1_clause_sdpi_r_required_actor_groupings>>.

[#vol1_figure_sdpi_r_actor_diagram]
.SDPi-R Actor Diagram

image::../images/vol1-diagram-sdpi-r-actor.svg[]

{empty} +

[#vol1_table_sdpi_r_actors_transactions]
.SDPi-R Profile - Actors and Transactions
[%autowidth]
[cols="1,2,1,1,3"]
|===
.^|Actors
.^|Transactions
.^|Initiator or Responder
.^|Optionality
.^|Reference

| ...
| #TABLE TO BE EXPANDED --.#
#279 - Mark DEV-36 & DEV-39 as Receiver --.#
#_Receiver_  ^(See^ ^Note^ ^2)^#
| ...
| ...
| ...

|===

// 11.1.1
==== Actor Descriptions and Actor Profile Requirements

// 11.2
=== SDPi-R Actor Options

// 11.2.1
==== tbd Option
// NOTE:  These options are TBD for SDPi 1.0

// 11.3
[#vol1_clause_sdpi_r_required_actor_groupings]
=== SDPi-R Required Actor Groupings

// 11.4
=== SDPi-R Overview

// 11.4.1
==== Concepts

// 11.4.2
==== Use Cases
The SDPi-R profile supports requirements from use cases detailed in <<vol1_appendix_c_dpi_use_cases>>.  The following subsections identify the specific use case requirements that are fulfilled with capabilities provided by this profile.


===== <<label_use_case_name_sicdsp>> (<<acronym_sicdsp>>)
This use case provides capabilities for requirements from <<vol1_clause_appendix_c_use_case_sicdsp>>.

Specific capabilities supporting the <<acronym_sicdsp>> use case include:

* *System Type*:  N/A
* *Service Type*:  N/A
* *Technical Pre-Conditions*: N/A
* *Scenarios*: <<acronym_sicdsp>> <<vol1_clause_appendix_c_use_case_sicdsp_scenarios>> communication of medical data to a <<actor_somds_consumer>> <<system_type_dashboard>>


===== <<label_use_case_name_sicdmp>> (<<acronym_sicdmp>>)
This use case provides capabilities for requirements from <<vol1_clause_appendix_c_use_case_sicdmp>>.

Specific capabilities supporting the <<acronym_sicdmp>> use case include:

* *System Type*:  N/A
* *System Type*:  N/A
* *Technical Pre-Conditions*: N/A
* *Scenarios*: <<acronym_sicdmp>> <<vol1_clause_appendix_c_use_case_sicdmp_scenarios>> communication of medical data to a <<actor_somds_consumer>> <<system_type_dashboard>>


===== <<label_use_case_name_ddes>> (<<acronym_ddes>>)
This use case provides capabilities for requirements from <<vol1_clause_appendix_c_use_case_ddes>>.

Specific capabilities supporting the <<acronym_ddes>> use case include:

* *System Type*:  N/A
* *Service Type*: N/A
* *Technical Pre-Conditions*: N/A
* *Scenarios*: <<acronym_ddes>> <<vol1_clause_appendix_c_use_case_ddes_scenarios>> communication of medical data to a <<actor_somds_consumer>> <<system_type_device_gateway>>

#TODO:  Reference DEC Gateway / DOR actor from generic use case scenario reference#

[#vol1_clause_sdpi_r_ses_considerations]
=== SDPi-R Safety, Effectiveness, Security Considerations and Requirements

==== SES General Considerations
Requirements from the <<ref_iso_81001_1_2021>>, <<ref_iec_80001_1_2021>>, and related standards should be fully applied to this technical framework element.

For additional guidance, see section <<vol1_clause_appendix_a_ses_considerations_and_requirements>>.

==== Safety Requirements & Considerations
No additional safety requirements or considerations are identified for this technical framework element beyond those specified in the _<<acronym_ses>> General Considerations_ section above.

==== Effectiveness Requirements & Considerations
No additional effectiveness requirements or considerations are identified for this technical framework element beyond those specified in the _<<acronym_ses>> General Considerations_ section above.

==== Security Requirements & Considerations
No additional security requirements and considerations are identified for this technical framework element beyond those provided by the  SDPi-P profile (see <<vol1_clause_appendix_a_ses_considerations_section_template>>), and those specified in the _<<acronym_ses>> General Considerations_ section above.

=== SDPi-R Cross Profile Considerations

No cross profile considerations have been identified.

////
#TODO:  See the template instructions + PCD 2019 and other TF's to see if any content should go in this section for SDPi-R.#
////

