= Service-oriented Device Point-of-care Interoperability - Alerting (SDPi-A) Profile

// 12.
[sdpi_offset=12]
== Service-oriented Device Point-of-care Interoperability - Alerting (SDPi-A) Profile

The SDPi-Alerting ([[acronym_sdpi_a,SDPi-A]] SDPi-A) profile supports #TODO: add general description ...#

// 12.1
=== SDPi-A Actors, Transactions, and Content Modules

This section defines the actors, transactions, and/or content modules in this profile.
General definitions of actors are given in the https://profiles.ihe.net/GeneralIntro/ch-A.html[_Technical Frameworks General Introduction Appendix A_].
IHE Transactions can be found in the https://profiles.ihe.net/GeneralIntro/ch-B.html[_Technical Frameworks General Introduction Appendix B_].
Both appendices are located at https://profiles.ihe.net/GeneralIntro/[_profiles.ihe.net/GeneralIntro_].

#Figure 12.1-1# shows the actors directly involved in the SDPi-A Profile.
The relevant transactions between them are detailed in the subsequent #Table 12.1-1#.
Actor groupings, including abstract with concrete are detailed in #Section 12.3#.

.SDPi-A Actor Diagram

image::../images/vol1-diagram-sdpi-a-actor.svg[]


// 12.1.1
==== Actor Descriptions and Actor Profile Requirements

// 12.2
=== SDPi-A Actor Options

// 12.2.1
==== tbd Option
// NOTE:  These options are TBD for SDPi 1.0

// 12.3
=== SDPi-A Required Actor Groupings

// 12.4
=== SDPi-A Overview

// 12.4.1
==== Concepts

// 12.4.2
==== Use Cases
The SDPi-A profile supports requirements from the use cases detailed in <<vol1_appendix_c_dpi_use_cases>>.  The following subsections identify the specific use case requirements that are fulfilled with capabilities provided by this profile.


===== Standalone ICU Dashboard Single Patient (SICDsp)
This profile provides capabilities for requirements from <<vol1_clause_appendix_c_use_case_sicdsp>>.

Specific capabilities supporting the SICDsp profile include:

* *System Type*:  N/A
* *Service Type*:  N/A
* *Technical Pre-Conditions*: N/A
* *Scenarios*: SICDsp <<vol1_clause_appendix_c_use_case_sicdsp_scenarios>> communication of medical alert information to a <<actor_somds_consumer>> <<system_type_dashboard>>



===== Standalone ICU Dashboard Multiple Patient (SICDmp)
This profile provides capabilities for requirements from <<vol1_clause_appendix_c_use_case_sicdmp>>.

Specific capabilities supporting the SICDmp profile include:

* *System Type*:  N/A
* *System Type*:  N/A
* *Technical Pre-Conditions*: N/A
* *Scenarios*: SICDmp <<vol1_clause_appendix_c_use_case_sicdmp_scenarios>> communication of medical alert information to a <<actor_somds_consumer>> <<system_type_dashboard>>


===== Alerts to Clinician Notification Systems (ACNS)
This profile provides capabilities for requirements from <<vol1_clause_appendix_c_use_case_acns>>.

Specific capabilities supporting the ACNS profile include:

* *System Type*:  N/A
* *Service Type*:  N/A
* *Technical Pre-Conditions*:  N/A
* *Scenarios*:  ACNS <<vol1_clause_appendix_c_use_case_acns_scenarios>> communication of medical alert information to a <<actor_somds_consumer>> Alert <<system_type_device_gateway>>


===== Alerts to Alert Recording Systems (AARS)
This profile provides capabilities for requirements from <<vol1_clause_appendix_c_use_case_aars>>.

Specific capabilities supporting the AARS profile include:

* *System Type*:  N/A
* *Service Type*:  N/A
* *Technical Pre-Conditions*:  N/A
* *Scenarios*:  AARS <<vol1_clause_appendix_c_use_case_aars_scenarios>> communication of medical alert information to a <<actor_somds_consumer>> Alert <<system_type_device_gateway>>


// 12.5
=== SDPi-A Safety, Effectiveness, Security Considerations and Requirements

// 12.5.1
==== SES General Considerations
Requirements from the <<ref_iso_81001_1_2021>>, <<ref_iec_80001_1_2021>>, and related standards should be fully applied to this technical framework element.

For additional guidance, see section <<vol1_clause_appendix_a_ses_considerations_and_requirements>>.

// 12.5.2
==== Safety Requirements & Considerations
No additional safety requirements or considerations are identified for this technical framework element beyond those specified in the _<<acronym_ses>> General Considerations_ section above.

// 12.5.3
==== Effectiveness Requirements & Considerations
No additional effectiveness requirements or considerations are identified for this technical framework element beyond those specified in the _<<acronym_ses>> General Considerations_ section above.

// 12.5.4
==== Security Requirements & Considerations
No additional security requirements and considerations are identified for this technical framework element beyond those provided by the  SDPi-P profile, and those specified in the _<<acronym_ses>> General Considerations_ section above.

// 12.6
=== SDPi-A Cross Profile Considerations
#TODO:  See the template instructions + PCD 2019 and other TF's to see if any content should go in this section for SDPi-A.#

