= Service-oriented Device Point-of-care Interoperability - Alerting (SDPi-A) Profile

// 12.
[sdpi_offset=12]
== Service-oriented Device Point-of-care Interoperability - Alerting (SDPi-A) Profile

// 12.1
=== SDPi-A Actors, Transactions, and Content Modules

This section defines the actors, transactions, and/or content modules in this profile.
General definitions of actors are given in the https://profiles.ihe.net/GeneralIntro/ch-A.html[_Technical Frameworks General Introduction Appendix A_].
IHE Transactions can be found in the https://profiles.ihe.net/GeneralIntro/ch-B.html[_Technical Frameworks General Introduction Appendix B_].
Both appendices are located at https://profiles.ihe.net/GeneralIntro/[_profiles.ihe.net/GeneralIntro_].

#Figure 12.1-1# shows the actors directly involved in the SDPi-A Profile.
The relevant transactions between them are detailed in the subsequent #Table 12.1-1#.
Actor groupings, including abstract with concrete are detailed in #Section 12.3#.

.SDPi-A Actor Diagram

image::../images/vol1-diagram-sdpi-a-actor.svg[]


// 12.1.1
==== Actor Descriptions and Actor Profile Requirements

// 12.2
=== SDPi-A Actor Options

// 12.2.1
==== tbd Option
// NOTE:  These options are TBD for SDPi 1.0

// 12.3
=== SDPi-A Required Actor Groupings

// 12.4
=== SDPi-A Overview

// 12.4.1
==== Concepts

// 12.4.2
==== Use Cases

// 12.5
=== SDPi-A Safety, Effectiveness, Security Considerations and Requirements

// 12.5.1
==== SES General Considerations

// 12.5.2
==== Safety Requirements & Considerations

// 12.5.3
==== Effectiveness Requirements & Considerations

// 12.5.4
==== Security Requirements & Considerations

// 12.6
=== SDPi-A Cross Profile Considerations

