// = Service-oriented Device Point-of-care Interoperability – external Control (SDPi-xC) Profile

// 13.
[#vol1_clause_sdpi_xc_profile,sdpi_offset=13]
== Service-oriented Device Point-of-care Interoperability – external Control (SDPi-xC) Profile


[%noheader]
[%autowidth]
[cols="1"]
|===
a| *SDPi Supplement Version Note*: This SDPi-xC (External Control) profile section is generally out-of-scope for the SDPi 1.0 version (see https://github.com/IHE/sdpi-fhir/wiki/SDPi-Editorial-Planning-and-Versions#sdpi-version-10-detail-[wiki article "SDPi Version 1.0 (Detail)"]); however, it is provided here to indicate the intended direction of the SDPi profiles, with details being added in subsequent versions.  Depending on capabilities, some very basic controls may need to be provided in 2023 as part of the 1.x or 2.0 versions, especially around external adjustment of settings (e.g., alert limits or to trigger a blood-pressure reading).

|===

The SDPi-External Control ([[acronym_sdpi_xc,SDPi-xC]] SDPi-xC) profile supports #TODO: add general description ...#

// 13.1
=== SDPi-xC Actors, Transactions, and Content Modules

This section defines the actors, transactions, and/or content modules in this profile.
General definitions of actors are given in the https://profiles.ihe.net/GeneralIntro/ch-A.html[_Technical Frameworks General Introduction Appendix A_].
IHE Transactions can be found in the https://profiles.ihe.net/GeneralIntro/ch-B.html[_Technical Frameworks General Introduction Appendix B_].
Both appendices are located at https://profiles.ihe.net/GeneralIntro/[_profiles.ihe.net/GeneralIntro_].

<<vol1_figure_sdpi_xc_actor_diagram>> shows the actors directly involved in the SDPi-xC profile.
The relevant transactions between them are detailed in the subsequent <<vol1_table_sdpi_xc_actors_transactions>>.
Actor groupings, including abstract with concrete are detailed in <<vol1_clause_sdpi_xc_required_actor_groupings>>.

[#vol1_figure_sdpi_xc_actor_diagram]
.SDPi-xC Actor Diagram

image::../images/vol1-diagram-sdpi-xc-actor.svg[]

[#vol1_table_sdpi_xc_actors_transactions]
.SDPi-xC Profile - Actors and Transactions
[%autowidth]
[cols="1,2,1,1,3"]
|===
.^|Actors
.^|Transactions
.^|Initiator or Responder
.^|Optionality
.^|Reference

| ...
| #TABLE TO BE EXPANDED#
| ...
| ...
| ...

|===

// 13.1.1
==== Actor Descriptions and Actor Profile Requirements

// 13.2
=== SDPi-xC Actor Options

// 13.2.1
==== tbd Option
// NOTE:  These options are TBD for SDPi 1.0

// 13.3
[#vol1_clause_sdpi_xc_required_actor_groupings]
=== SDPi-xC Required Actor Groupings

// 13.4
=== SDPi-xC Overview

// 13.4.1
==== Concepts

// 13.4.2
==== Use Cases

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *SDPi Supplement Version Note*:  _*For SDPi 1.0*_, no use cases have been included that provide functional requirements for device external control.  These will be added to a future version of the SDPi supplement.
For this SDPi 1.0 DEV Internal Review Version, this profile section remains incomplete, with significant content needing to be migrated from the Word version of the supplement and then integrated into this AsciiDoc specification.
This will be completed in January and *_an updated DEV Internal Review Version published by mid-January_*.
|===

[#vol1_clause_sdpi_xc_ses_considerations]
=== SDPi-xC Safety, Effectiveness, Security Considerations and Requirements

==== SES General Considerations
Requirements from the <<ref_iso_81001_1_2021>>, <<ref_iec_80001_1_2021>>, and related standards should be fully applied to this technical framework element.

For additional guidance, see section <<vol1_clause_appendix_a_ses_considerations_and_requirements>>.

==== Safety Requirements & Considerations
No additional safety requirements or considerations are identified for this technical framework element beyond those specified in the _<<acronym_ses>> General Considerations_ section above.

==== Effectiveness Requirements & Considerations
No additional effectiveness requirements or considerations are identified for this technical framework element beyond those specified in the _<<acronym_ses>> General Considerations_ section above.

==== Security Requirements & Considerations
No additional security requirements and considerations are identified for this technical framework element beyond those provided by the  SDPi-P profile (see <<vol1_clause_appendix_a_ses_considerations_section_template>>), and those specified in the _<<acronym_ses>> General Considerations_ section above.

=== SDPi-xC Cross Profile Considerations

No cross profile considerations have been identified.

////
#TODO:  See the template instructions + PCD 2019 and other TF's to see if any content should go in this section for SDPi-xC.#
////

