// = Service-oriented Device Point-of-care Interoperability - Reporting (SDPi-R) Profile

// 11.
[#vol1_clause_sdpi__r_profile,sdpi_offset=11]
== Service-oriented Device Point-of-care Interoperability - Reporting (SDPi-R) Profile

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *SDPi Supplement Version Note*:  For SDPi 1.0 DEV Internal Review Version, this profile section remains fairly incomplete, with significant content needing to be migrated from the Word version of the supplement and then integrated into this AsciiDoc specification.
This will be completed in early January and *_an updated DEV Internal Review Version published by mid-January_*.

Note that the related transactions are completely defined in <<vol2_clause_transactions>>, and the <<actor_somds_dec_gateway>> is fully specified in <<#vol2_clause_appendix_sdpi_dec_gateway>>.
|===


The SDPi-Reporting ([[acronym_sdpi_r,SDPi-R]] SDPi-R) profile supports #TODO: add general description ...#

// 11.1
=== SDPi-R Actors, Transactions, and Content Modules

This section defines the actors, transactions, and/or content modules in this profile.
General definitions of actors are given in the https://profiles.ihe.net/GeneralIntro/ch-A.html[_Technical Frameworks General Introduction Appendix A_].
IHE Transactions can be found in the https://profiles.ihe.net/GeneralIntro/ch-B.html[_Technical Frameworks General Introduction Appendix B_].
Both appendices are located at https://profiles.ihe.net/GeneralIntro/[_profiles.ihe.net/GeneralIntro_].

#Figure 11.1-1# shows the actors directly involved in the SDPi-R Profile.
The relevant transactions between them are detailed in the subsequent #Table 11.1-1#.
Actor groupings, including abstract with concrete are detailed in #Section 11.3#.

.SDPi-R Actor Diagram

image::../images/vol1-diagram-sdpi-r-actor.svg[]

// 11.1.1
==== Actor Descriptions and Actor Profile Requirements

// 11.2
=== SDPi-R Actor Options

// 11.2.1
==== tbd Option
// NOTE:  These options are TBD for SDPi 1.0

// 11.3
=== SDPi-R Required Actor Groupings

// 11.4
=== SDPi-R Overview

// 11.4.1
==== Concepts

// 11.4.2
==== Use Cases
The SDPi-R profile supports requirements from the use cases detailed in <<vol1_appendix_c_dpi_use_cases>>.  The following subsections identify the specific use case requirements that are fulfilled with capabilities provided by this profile.


===== Standalone ICU Dashboard Single Patient (SICDsp)
This profile provides capabilities for requirements from <<vol1_clause_appendix_c_use_case_sicdsp>>.

Specific capabilities supporting the SICDsp profile include:

* *System Type*:  N/A
* *Service Type*:  N/A
* *Technical Pre-Conditions*: N/A
* *Scenarios*: SICDsp <<vol1_clause_appendix_c_use_case_sicdsp_scenarios>> communication of medical data to a <<actor_somds_consumer>> <<system_type_dashboard>>


===== Standalone ICU Dashboard Multiple Patient (SICDmp)
This profile provides capabilities for requirements from <<vol1_clause_appendix_c_use_case_sicdmp>>.

Specific capabilities supporting the SICDmp profile include:

* *System Type*:  N/A
* *System Type*:  N/A
* *Technical Pre-Conditions*: N/A
* *Scenarios*: SICDmp <<vol1_clause_appendix_c_use_case_sicdmp_scenarios>> communication of medical data to a <<actor_somds_consumer>> <<system_type_dashboard>>


===== Device Data to Enterprise Systems (<<acronym_ddes>)
This profile provides capabilities for requirements from <<vol1_clause_appendix_c_use_case_ddes>>.

Specific capabilities supporting the DDES profile include:

* *System Type*:  N/A
* *Service Type*: N/A
* *Technical Pre-Conditions*: N/A
* *Scenarios*: DDES <<vol1_clause_appendix_c_use_case_ddes_scenarios>> communication of medical data to a <<actor_somds_consumer>> <<system_type_device_gateway>>

#TODO:  Reference DEC Gateway / DOR actor from generic use case scenario reference#

// 11.5
=== SDPi-R Safety, Effectiveness, Security Considerations and Requirements

// 11.5.1
==== SES General Considerations
Requirements from the <<ref_iso_81001_1_2021>>, <<ref_iec_80001_1_2021>>, and related standards should be fully applied to this technical framework element.

For additional guidance, see section <<vol1_clause_appendix_a_ses_considerations_and_requirements>>.

// 11.5.2
==== Safety Requirements & Considerations
No additional safety requirements or considerations are identified for this technical framework element beyond those specified in the _<<acronym_ses>> General Considerations_ section above.

// 11.5.3
==== Effectiveness Requirements & Considerations
No additional effectiveness requirements or considerations are identified for this technical framework element beyond those specified in the _<<acronym_ses>> General Considerations_ section above.

// 11.5.4
==== Security Requirements & Considerations
No additional security requirements and considerations are identified for this technical framework element beyond those provided by the  SDPi-P profile, and those specified in the _<<acronym_ses>> General Considerations_ section above.

// 11.6
=== SDPi-R Cross Profile Considerations
#TODO:  See the template instructions + PCD 2019 and other TF's to see if any content should go in this section for SDPi-R.#

