= Service-oriented Device Point-of-care Interoperability – external Control (SDPi-xC) Profile

// 13.
[sdpi_offset=13]
== Service-oriented Device Point-of-care Interoperability – external Control (SDPi-xC) Profile


[%noheader]
[%autowidth]
[cols="1"]
|===
a| *SDPi Supplement Version Note*: This SDPi-xC (External Control) profile section is generally out-of-scope for the SDPi 1.0 version (see https://github.com/IHE/sdpi-fhir/wiki/SDPi-Editorial-Planning-and-Versions#sdpi-version-10-detail-[wiki article "SDPi Version 1.0 (Detail)"]); however, it is provided here to indicate the intended direction of the SDPi profiles, with details being added in subsequent versions.  Depending on capabilities, some very basic controls may need to be provided in 2023 as part of the 1.x or 2.0 versions, especially around external adjustment of settings (e.g., alert limits or to trigger a blood-pressure reading).

|===

// 13.1
=== SDPi-xC Actors, Transactions, and Content Modules

This section defines the actors, transactions, and/or content modules in this profile.
General definitions of actors are given in the https://profiles.ihe.net/GeneralIntro/ch-A.html[_Technical Frameworks General Introduction Appendix A_].
IHE Transactions can be found in the https://profiles.ihe.net/GeneralIntro/ch-B.html[_Technical Frameworks General Introduction Appendix B_].
Both appendices are located at https://profiles.ihe.net/GeneralIntro/[_profiles.ihe.net/GeneralIntro_].

#Figure 13.1-1# shows the actors directly involved in the SDPi-R Profile.
The relevant transactions between them are detailed in the subsequent #Table 13.1-1#.
Actor groupings, including abstract with concrete are detailed in #Section 13.3#.

.SDPi-xC Actor Diagram

image::../images/vol1-diagram-sdpi-xc-actor.svg[]

// 13.1.1
==== Actor Descriptions and Actor Profile Requirements

// 13.2
=== SDPi-xC Actor Options

// 13.2.1
==== tbd Option
// NOTE:  These options are TBD for SDPi 1.0

// 13.3
=== SDPi-xD Required Actor Groupings

// 13.4
=== SDPi-xC Overview

// 13.4.1
==== Concepts

// 13.4.2
==== Use Cases

// 13.5
=== SDPi-xC Safety, Effectiveness, Security Considerations and Requirements

// 13.5.1
==== SES General Considerations

// 13.5.2
==== Safety Requirements & Considerations

// 13.5.3
==== Effectiveness Requirements & Considerations

// 13.5.4
==== Security Requirements & Considerations

// 13.6
=== SDPi-xC Cross Profile Considerations

