= Service-oriented Device Point-of-care Interoperability - Reporting (SDPi-R) Profile

// 11.
[sdpi_offset=11]
== Service-oriented Device Point-of-care Interoperability - Reporting (SDPi-R) Profile

The SDPi-Reporting ([[acronym_sdpi_r,SDPi-R]] SDPi-R) profile supports #TODO: add general description ...#

// 11.1
=== SDPi-R Actors, Transactions, and Content Modules

This section defines the actors, transactions, and/or content modules in this profile.
General definitions of actors are given in the https://profiles.ihe.net/GeneralIntro/ch-A.html[_Technical Frameworks General Introduction Appendix A_].
IHE Transactions can be found in the https://profiles.ihe.net/GeneralIntro/ch-B.html[_Technical Frameworks General Introduction Appendix B_].
Both appendices are located at https://profiles.ihe.net/GeneralIntro/[_profiles.ihe.net/GeneralIntro_].

#Figure 11.1-1# shows the actors directly involved in the SDPi-R Profile.
The relevant transactions between them are detailed in the subsequent #Table 11.1-1#.
Actor groupings, including abstract with concrete are detailed in #Section 11.3#.

.SDPi-R Actor Diagram

image::../images/vol1-diagram-sdpi-r-actor.svg[]

// 11.1.1
==== Actor Descriptions and Actor Profile Requirements

// 11.2
=== SDPi-R Actor Options

// 11.2.1
==== tbd Option
// NOTE:  These options are TBD for SDPi 1.0

// 11.3
=== SDPi-R Required Actor Groupings

// 11.4
=== SDPi-R Overview

// 11.4.1
==== Concepts

// 11.4.2
==== Use Cases

// 11.5
=== SDPi-R Safety, Effectiveness, Security Considerations and Requirements

// 11.5.1
==== SES General Considerations

// 11.5.2
==== Safety Requirements & Considerations

// 11.5.3
==== Effectiveness Requirements & Considerations

// 11.5.4
==== Security Requirements & Considerations

// 11.6
=== SDPi-R Cross Profile Considerations

