include::tf2-ch-b-gateway-global-vars.adoc[]

= SDPi DEC Gateway -- Mapping

NOTE:  This file contains the SDPi gateway actor (SOMDS_DEC_Gateway) logic for mapping from SDC BICEPS MDIB content and interactions with IHE DEV "PCD" DEC profile messaging.

== Scope
This chapter defines the mapping from SDC MDIB content as defined in this document and its underlying standards, to IHE Device Enterprise Communication (DEC) profile messages as defined in the *{var_ihe_tf-2_long}*.

The SDPi gateway actor represents the Device Observation Reporter (DOR) role of the IHE DEC profile.

The following sections supplement the IHE DEC profile as appropriate. If there are no supplementing definitions, the definitions as described in the *{var_ihe_tf-2_short}* will apply.

== Referenced Standards & Profiles
This section provides an overview about the referenced standards and profiles used in this chapter:

* {var_ihe_tf-2_long}
* {var_sdc_std_10207}
* {var_sdc_std_10700}
* {var_sdc_std_10701}

== HL7 Segment Descriptions
The following sections refer to the *Appendix B Common Segment Descriptions* of the *{var_ihe_tf-2_long}*.

=== MSH - Message Header Segment
The HL7 Message Header (MSH) segment does not require a specific mapping between the SDC MDIB content and the HL7 DEC profile messages. In context of this chapter, the MSH segment content shall be in compliance with the [PCD-01] transaction as described in the {var_ihe_tf-2_short}.

#Todo: consider demo data#

include::tf2-ch-b-gateway-pid-mapping.adoc[]

include::tf2-ch-b-gateway-pv1-mapping.adoc[]

=== OBR - Observation Request Segment
The the HL7 Obervation Request (OBR) segment requires a mapping from the SDC containment tree and metric data to the OBR segment fields.

==== OBR-2 Placer Order Number
For IHE DEC profile, the OBR-2 field shall contain the identifier of the Device Observation Reporter (DOR) of the IHE DEC gateway (not the individual device identifier). For further information, please refer to the *{var_ihe_tf-2_short}*.

==== OBR-3 Filler Order Number
For the IHE DEC profile, the OBR-3 field shall contain the identifier of the Device Observation Reporter (DOR) of the IHE DEC gateway (not the individual device identifier). For further information, please refer to the *{var_ihe_tf-2_short}*.

==== OBR-4 Universal Service ID
For the IHE DEC profile, the OBR-4 field shall contain the service identifier of the device. For further information, please refer to the *{var_ihe_tf-2_short}*.

#Todo: how can we map the device type to the proposed SNOMED code from the SDC information? Should we use MDC codes instead? What about the licensing issue with SNOMED code?#

#Todo: special requirements for infusion pumps#

==== OBR-7 Observation Date/Time
The OBR-7 field shall contain the date & time of the continuously measured metrics to be exported with the same metric measurement timestamp. For episodic measurements and the absence of any continuously measured metrics for this export interval, the OBR-7 field shall be set to the oldest measurement timestamp of the episodic metrics to be exported in this interval.
The table <<ref_tbl_dec_obr7_mapping>> defines the mapping of the SDC metric measurement timestamp to the data fields of the HL7 data type *DTM* used in the OBR-7 field.

[NOTE]
Only metrics that fulfil certain criteria shall be exported by the gateway. Please refer to TBD for further information.

[#ref_tbl_dec_obr7_mapping]
.OBR-7 Metric Measurement Timestamp Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|OBR-7/DTM-1
|Date/Time
|pm:EnumStringMetricState
/pm:MetricValue
/@DeterminationTime

pm:NumericMetricState
/pm:MetricValue
/@DeterminationTime

pm:StringMetricState
/pm:MetricValue
/@DeterminationTime
|If *pm:AbstractMetricDescriptor /@MetricAvailability* is set to "*Cont*", the field shall be set to the *@DeterminationTime* of the continuously measured metrics to be exported in the same HL7 message with the same *@DeterminationTime*. Episodic metrics shall be exported in the same HL7 message, when their *@DeterminationTime* is equal or older than the *@DeterminationTime* of the continuously measured metrics.

If *pm:AbstractMetricDescriptor /@MetricAvailability* is set to "*Intr*" and if there are no continuously measured metrics to be exported, the field shall be set to the oldest *@DeterminationTime* of the episodic metrics to be exported in the same HL7 message.

Note that the HL7 date & time format differs from the xsd date/time formats and requires a mapping accordingly (see also <<ref_expl_dt_mapping>>).

|===

==== OBR-8 Observation End Date/Time
The OBR-8 field shall not be used for the SDPi DEC gateway.

==== OBR-10 Collector Identifier
#Todo: shall/could this field be mapped to the SDC user context?#

=== OBX - Observation/Result Segment
The the HL7 Obervation/Result (OBX) segment requires a mapping from the SDC containment tree and metric data to the OBX segment fields.

#Todo: MDS/VMD/CHAN OBX tbd#

==== OBX-2 Value Type
The OBX-2 field shall be set to the metric value type code as define in *HL7 table 0125*. The table <<ref_tbl_dec_obx2_mapping>> defines the mapping of the SDC metric type to the data fields of the HL7 data type *ID* used in the OBX-2 field.

[NOTE]
This field shall be left empty for OBX segments defining the device containment tree information such as MDS, VMD and CHAN.

[#ref_tbl_dec_obx2_mapping]
.OBX-2 Value Type Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|OBX-2/ID-1
|Coded Value for HL7-Defined Tables
|*"NM"* if the metric state is of type *pm:NumericMetricState*.

*"ST"* if the metric state is of type *pm:StringMetricState*.

*"CWE"* if the metric state is of type *pm:EnumStringMetricState*.

|

|===

==== OBX-3 Observation Identifier