The OBX-4 field shall contain a flattened representation of the SDC element in the hierarchical containment tree. Please refer to the IHE technical framework <<ihe_pcd_tf-2_2019>> for further information.

The gateway shall assign the handles (which are required to be unique in the same MDIB) of the containment tree elements pm:Mds, pm:Vmd, pm:Channel, and pm:Metic to unique integer numbers. The numbers have to be unique per contrainment tree level e. g. all pm:Vmd elements are assigned to a unique number. The pm:Channel elements may use the same numbers as the pm:Vmd elements but on the pm:Channel level the numbers must be unique as well.

There is no requirement to preserve the same assigned number for a containment tree element from message to message, but it is highly recommended since this makes it much easier for the DOC to process the HL7 V2 messages.

.Containment Tree Element Handle Assignment
====
The gateway assigns the handles of the containment tree elements to

* "3" for pm:Mds/@Handle="My1Mds".
* "1" for pm:Vmd/@Handle="Vmd.1".
* "2" for pm:Channel/@Handle="Chan.4".
* "1" for pm:Metric/@Handle="Metric.Spo2".

The OBX-4 field for the containment tree elements shall be set to

* "3.0.0.0" for the MDS OBX segment.
* "3.1.0.0" for the VMD OBX segment.
* "3.1.2.0" for the CHAN OBX segment.
* "3.1.2.1" for the Metric OBX segment.
====