===== PV1 - Patient Visit Segment
The HL7 Patient Visit (PV1) segment requires a mapping from the SDC patient and location context information to the PV1 segment fields.

.Prerequisite of Valid Patient & Location Context
[NOTE#ref_valid_pt_loc_ctxt_note]
====
The SDC patient and location context information shall only be mapped to the corresponding fields in the HL7 PV1 segment when the requirements (e. g. inferred patient and/or location ensemble context, associated patient and/or location context, etc.) as defined in the <<ieee_11073_10700_2022>> are fulfilled.

If the SDC patient and/or location context information shall not be used for the mapping, please refer to the <<ihe_pcd_tf-2_2019>> on how to populate the fields of the PV1 segment in this case.
====

====== PV1-2 Patient Class
The PV1-2 field shall contain the code for the patient class. The *HL7 table 0004 - Patient Class* defines a set of recommended codes to be used for the data fields of the HL7 data type *IS* used in the PV1-2 field.

Usually, a PoC device is used for patients admitted to a care unit in the hospital, and therefore, the field shall be set to *"I" (Inpatient)*. If the patient class is unknown, the field shall be set to *"U" (Unknown)*.

#Always set it to Unknown (default) for the mapping or configurable in the gateway#

#Todo: is there a way to get info about the patient class from the SDC provider? Or derive them from the device type?#

====== PV1-3 Assigned Patient Location
The PV1-3 field shall contain the patient's assigned location. The table <<ref_tbl_pv13_mapping>> defines the mapping of the SDC patient location information to the data fields of the HL7 data type *PL* used in the PV1-3 field.

[#ref_tbl_pv13_mapping]
.PV1-3 Patient Location Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PV1-3/PL-1
|Point of Care
|pm:LocationContextState
/pm:LocationDetail
/@PoC
|Aka. clinical care unit

|PV1-3/PL-2
|Room
|pm:LocationContextState
/pm:LocationDetail
/@Room
|

|PV1-3/PL-3
|Bed
|pm:LocationContextState
/pm:LocationDetail
/@Bed
|

|PV1-3/PL-4
|Facility
|pm:LocationContextState
/pm:LocationDetail
|HL7 data type *HD*

|PV1-3/PL-4.1
|Namespace ID
|/@Facility
|

|PV1-3/PL-7
|Building
|pm:LocationContextState
/pm:LocationDetail
/@Building
|

|PV1-3/PL-8
|Floor
|pm:LocationContextState
/pm:LocationDetail
/@Floor
|

|===

====== PV1-19 Visit Number
The PV1-19 field shall contain the patient's visit identifier (visit number, account number, etc.). The table <<ref_tbl_pv119_mapping>> defines the mapping of the SDC patient identifier to the data fields of the HL7 data type *CX* used in the PV1-19 field.

The SDC patient identifier element *pm:PatientContextState/pm:Identification* may contain more than one patient identifier. Only the unique identifier assigned to the patient's visit shall be mapped according to the <<ref_tbl_pv119_mapping>> table.

When there is no unique visit identifier assigned to the patient's visit, the field shall be left empty.

[#ref_tbl_pv119_mapping]
.PV1-19 Visit Number Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PV1-19/CX-1
|ID Number
|pm:PatientContextState
/pm:Identification
/@Extension
|The @Extension attribute contains the unique visit identifier if available.

*Note that the field may contain a null value indicating that the identifier is missing.*

|PV1-19/CX-4
|Assigning Authority
|pm:PatientContextState
/pm:Identification
| HL7 data type *HD*

|PV1-19/CX-4.1
|Namespace ID
|/@Root
|The @Root contains the unique identification of the HDO.

*Note that if the HDO identifer is not defined the CX-4 field shall be left empty.*

|PV1-19/CX-5
|Identifier Type Code
|pm:PatientContextState
/pm:Identification
/pm:Type
/@Code
|The type of the patient identifier set in the @Code attribute must be mapped HL7 table 0203.
#ToDo: what types does SDC support? how are the types coded?#

|===

====== PV1-44 Admit Time / Date
#Todo: how can the admit time / date be determined? Which admission time can a device provide - hospital admission, unit admission, device admission?#
Leave empty or gateway have to figure out the admission time

====== PV1-51 Visit Indicator
#Todo: can this be determined by the patient identifier type code in the Patient Context State/Identification?#

#If id is a visit number "VN" than set to "V" otherwise leave empty#

