=== SDPi DEC Gateway -- Mapping

==== Scope
This chapter defines the mapping from SDC MDIB content as defined in this document and its underlying standards, to IHE Device Enterprise Communication (DEC) profile messages as defined in the <<ihe_pcd_tf-2_2019>>.

The SDPi gateway actor represents the Device Observation Reporter (DOR) role of the IHE DEC profile.

The following sections supplement the IHE DEC profile as appropriate. If there are no supplementing definitions, the definitions as described in the <<ihe_pcd_tf-2_2019>> will apply.

==== Referenced Standards & Profiles
This section provides an overview about the referenced standards and profiles used in this chapter:

* <<ihe_pcd_tf-2_2019>>
* <<ieee_11073_10701_2022>>
* <<ieee_11073_10700_2022>>
* <<ieee_11073_10207_2017>>

[#ref_private_coding_system_note]
==== Private Coding System Consideration
The default coding system utilized in SDC is *"MDC"* (Medical Device Communications) also known as *"ISO/IEEE 11073-10101"* nomenclature.

In addition to the standard codes, *MDC* defines private code ranges that can be used by medical device vendors for defining their own codes, for example, for concepts for which standard codes do not exist. Private codes should be avoided whenever possible since this undermines interoperability.

Coded elements in SDC using *MDC* private codes shall also contain a *pm:Translation* element that defines the vendor-specific coding system.

The following example uses the SDC *pm:Type* to demonstrate the mapping of private MDC codes.

[#ref_tbl_private_code_mapping]
.Private Code Mapping (CWE data type example)
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|CWE-1
|Identifier
|pm:Type
/@Code
| This attribute contains the private *MDC* code.

|CWE-2
|Text
|"*MDC_PRIVATE_*<CWE-1>"
|Since this is a private code, a MDC RefId does not exist for the code. The field shall be set to a private RefId which consists of the prefix *"MDC_PRIVATE_"* plus the private code set in CWE-1.

|CWE-3
|Name of Coding System
|
|Set to coding system *"MDC"*.

|CWE-4
|Alternate Identifier
|pm:Type
/pm:Translation
/@Code
|This code shall be identical with the *pm:Type/@Code* attribute.

|CWE-6
|Name of Alternate Coding System
|pm:Type
/pm:Translation
/@CodingSystem
|This attribute specifies the vendor-specific or local coding system that has defined the private *MDC* code.

|CWE-7
|Coding System Version ID
|pm:Type
/@CodingSystemVersion
|

|CWE-8
|Alternate Coding System Version ID
|pm:Type
/pm:Translation
/@CodingSystemVersion
|

|===

.MDC Private Code Mapping Output
====
123455\^MDC_PRIVATE_123455^MDC\^123455^^urn:oid:1.3.6.1.4.1.1234.2

123455\^MDC_PRIVATE_123455^MDC\^123455^^99PHL
====

==== HL7 Segment Descriptions
The following sections refer to the *Appendix B Common Segment Descriptions* of the <<ihe_pcd_tf-2_2019>>.

include::tf2-ch-b-gateway-msh-mapping.adoc[]

include::tf2-ch-b-gateway-pid-mapping.adoc[]

===== Height and Weight Mapping
The *pm:PatientContextState/pm:CoreData* element may also contain elements for patient's height and/or weight. If available, the height and weight shall be exported as OBX segments on the MDS level. The mapping for the height observation is defined in table <<ref_tbl_dec_obx_height_mapping>> and the weight mapping in table <<ref_tbl_dec_obx_weight_mapping>>.

.Height/Weight Observation Date Time Consideration
[NOTE#ref_height_weight_dt_issue_note]
====
In the SDC Domain Information and Service Model, there are no explicit timestamps for the heigt and weight observation in *pm:PatientContextState/pm:CoreData* element. The only timestamp associated timestamp with the current patient context state is the *pm:PatientContextState/@BindingStartTime*, but this timestamp is set only once when the context was associated regardless whether height and weight has been set or updated later.

The gateway could also keep track of the *pm:PatientContextState* updates and evaluate height/weight value changes in the state updates. The state update timestamp has to be set by the SDC gateway consumer when it receives the new context state. That timestamp could be used for the height and/or weight observation that has been changed. The problem is that when the gateway loses connection to the PoC device it can only get the latest state update with a new version number but there is no timestamp related to the new state.

Therefore, the gateway shall use the *pm:PatientContextState/@BindingStartTime* as the timestamp for the height and weight observation and send new values as corrected results.
====

[#ref_tbl_dec_obx_height_mapping]
.OBX Height Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|OBX-1
|Set ID - OBX
|
|Please refer to the <<ihe_pcd_tf-2_2019>> *OBX-1 Set ID - OBX* for further information

|OBX-2
|Value Type
|
|Set to *"NM"* since height is always represented as a decimal number.

|OBX-3/CWE-1
|Identifier
|
|Set to MDC code *"68060"*.

|OBX-3/CWE-2
|Text
|
| Set to MDC RefId *"MDC_ATTR_PT_HEIGHT"*.

|OBX-3/CWE-3
|Name of Coding System
|
|Set to coding system *"MDC"*.

|OBX-4
|Observation Sub-ID
|
|Set to *"<MDS>.0.0.1"* where *<MDS>* is the number of the MDS level assigned by the gateway.
See <<ref_dec_obx4>> for further information.

|OBX-5
|Observation Value
|pm:PatientContextState
/pm:CoreData
/pm:Height
/@MeasuredValue
|Note that the decimal number shall be formatted according the HL7 numeric value formatting rules.

|OBX-6
|Units
|
|HL7 data type *CWE*

|OBX-6/CWE-1
|Identifier
|pm:PatientContextState
/pm:CoreData
/pm:Height
/pm:MeasurementUnit
/@Code
|

|OBX-6/CWE-2
|Text
|If @Code is an MDC code, this field shall contain the RefId of the MDC code.

In all other cases, the field shall be set to the pm:PatientContextState
/pm:CoreData
/pm:Height
/pm:MeasurementUnit
/@SymbolicCodeName.
|Note that MDC is the default coding system if no coding system is specified.

|OBX-6/CWE-3
|Name of Coding System
|*"MDC"* if no other coding system is specified.

In all other cases, the field shall be set to pm:PatientContextState
/pm:CoreData
/pm:Height
/pm:MeasurementUnit
/@CodingSystem.
|Note that MDC is the default coding system if no coding system is specified.

|OBX-11
|Observation Result Status
|
|When the patient context has been associated and a new *@BindingStartTime* has been set, the field shall be set to final result status *"F"*.

When there are further updates of the height value after the association of the patient context, the field shall be set to *"C"*.

|OBX-14
|Date/Time of the Observation
|pm:PatientContextState
/@BindingStartTime
|Note that the HL7 date & time format differs from the xsd date/time formats and requires a mapping accordingly (see also <<ref_expl_dt_mapping>>).

|===


[#ref_tbl_dec_obx_weight_mapping]
.OBX Weight Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|OBX-1
|Set ID - OBX
|
|Please refer to the <<ihe_pcd_tf-2_2019>> *OBX-1 Set ID - OBX* for further information

|OBX-2
|Value Type
|
|Set to *"NM"* since weight is always represented as a decimal number.

|OBX-3/CWE-1
|Identifier
|
|Set to MDC code *"68063"*.

|OBX-3/CWE-2
|Text
|
| Set to MDC RefId *"MDC_ATTR_PT_WEIGHT"*.

|OBX-3/CWE-3
|Name of Coding System
|
|Set to coding system *"MDC"*.

|OBX-4
|Observation Sub-ID
|
|Set to *"<MDS>.0.0.2"* where *<MDS>* is the number of the MDS level assigned by the gateway.
See <<ref_dec_obx4>> for further information.

|OBX-5
|Observation Value
|pm:PatientContextState
/pm:CoreData
/pm:Weight
/@MeasuredValue
|Note that the decimal number shall be formatted according the HL7 numeric value formatting rules.

|OBX-6
|Units
|
|HL7 data type *CWE*

|OBX-6/CWE-1
|Identifier
|pm:PatientContextState
/pm:CoreData
/pm:Weight
/pm:MeasurementUnit
/@Code
|

|OBX-6/CWE-2
|Text
|If @Code is an MDC code, this field shall contain the RefId of the MDC code.

In all other cases, the field shall be set to the pm:PatientContextState
/pm:CoreData
/pm:Weight
/pm:MeasurementUnit
/@SymbolicCodeName.
|Note that MDC is the default coding system if no coding system is specified.

|OBX-6/CWE-3
|Name of Coding System
|*"MDC"* if no other coding system is specified.

In all other cases, the field shall be set to pm:PatientContextState
/pm:CoreData
/pm:Weight
/pm:MeasurementUnit
/@CodingSystem.
|Note that MDC is the default coding system if no coding system is specified.

|OBX-11
|Observation Result Status
|
|When the patient context has been associated and a new @BindingStartTime has been set, the field shall be set to final result status "F".

When there are further updates of the weight value after the association of the patient context, the field shall be set to "C".

|OBX-14
|Date/Time of the Observation
|pm:PatientContextState
/@BindingStartTime
|Note that the HL7 date & time format differs from the xsd date/time formats and requires a mapping accordingly (see also <<ref_expl_dt_mapping>>).

|===

include::tf2-ch-b-gateway-pv1-mapping.adoc[]

===== OBR - Observation Request Segment
The the HL7 Obervation Request (OBR) segment requires a mapping from the SDC containment tree and metric data to the OBR segment fields.

====== OBR-2 Placer Order Number
For IHE DEC profile, the OBR-2 field shall contain the identifier of the Device Observation Reporter (DOR) of the IHE DEC gateway (not the individual device identifier). For further information, please refer to the <<ihe_pcd_tf-2_2019>>.

====== OBR-3 Filler Order Number
For the IHE DEC profile, the OBR-3 field shall contain the identifier of the Device Observation Reporter (DOR) of the IHE DEC gateway (not the individual device identifier). For further information, please refer to the <<ihe_pcd_tf-2_2019>>.

====== OBR-4 Universal Service ID
For the IHE DEC profile, the OBR-4 field shall contain the service identifier of the device. For further information, please refer to the <<ihe_pcd_tf-2_2019>>.

#Todo: how can we map the device type to the proposed SNOMED code from the SDC information? Should we use MDC codes instead? What about the licensing issue with SNOMED code?#

#Todo: special requirements for infusion pumps#

#Todo: Todd owns issue regarding the service ids.#

====== OBR-7 Observation Date/Time
The OBR-7 field shall contain the date & time of the continuously measured metrics to be exported with the same metric measurement timestamp. For episodic measurements and the absence of any continuously measured metrics for this export interval, the OBR-7 field shall be set to the oldest measurement timestamp of the episodic metrics to be exported in this interval.
The table <<ref_tbl_dec_obr7_mapping>> defines the mapping of the SDC metric measurement timestamp to the data fields of the HL7 data type *DTM* used in the OBR-7 field.

[NOTE]
Only metrics that fulfil certain criteria shall be exported by the gateway. Please refer to TBD for further information.

[#ref_tbl_dec_obr7_mapping]
.OBR-7 Metric Measurement Timestamp Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|OBR-7/DTM-1
|Date/Time
|pm:EnumStringMetricState
/pm:MetricValue
/@DeterminationTime

pm:NumericMetricState
/pm:MetricValue
/@DeterminationTime

pm:StringMetricState
/pm:MetricValue
/@DeterminationTime
|If *pm:AbstractMetricDescriptor /@MetricAvailability* is set to "*Cont*", the field shall be set to the *@DeterminationTime* of the continuously measured metrics to be exported in the same HL7 message with the same *@DeterminationTime*. Episodic metrics shall be exported in the same HL7 message, when their *@DeterminationTime* is equal or older than the *@DeterminationTime* of the continuously measured metrics.

If *pm:AbstractMetricDescriptor /@MetricAvailability* is set to "*Intr*" and if there are no continuously measured metrics to be exported, the field shall be set to the oldest *@DeterminationTime* of the episodic metrics to be exported in the same HL7 message.

Note that the HL7 date & time format differs from the xsd date/time formats and requires a mapping accordingly (see also <<ref_expl_dt_mapping>>).

|===

====== OBR-8 Observation End Date/Time
The OBR-8 field shall not be used for the SDPi DEC gateway.

====== OBR-10 Collector Identifier
The OBR-10 field shall contain the operator (user) information if available. The table <<ref_tbl_OBR10_mapping>> defines the mapping of the SDC operator context information to the data fields of the HL7 data type *XCN* used in the OBR-10 field.

[NOTE]
====
The SDC operator context is only valid when the *pm:OperatorContextState/@ContextAssociation* is set to *"Assoc"* and a *pm:OperatorContextState/@BindingStartTime* is set.

The field shall be left empty if there is no valid SDC operator context.
====

[#ref_tbl_OBR10_mapping]
.OBR-10 Operator Information Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|OBR-10/XCN-1
|ID Number
|pm:OperatorContextState
/pm:Identification
/@Extension
|The @Extension attribute contains the unique operator identifier.

*Note that the field may contain a null value indicating that the identifier is missing.*

|OBR-10/XCN-2
|Family Name
|pm:OperatorContextState
/pm:OperatorDetails
|HL7 data type *FN*

|OBR-10/XCN-2.1
|Surname
|/pm:Familyname
|

|OBR-10/XCN-3
|Given Name
|pm:OperatorContextState
/pm:OperatorDetails
/pm:Givenname
|

|OBR-10/XCN-4
|Second and Further Given Names or Initials
|pm:OperatorContextState
/pm:OperatorDetails
/pm:Middlename
|

|OBR-10/XCN-6
|Prefix (e.g. DR)
|pm:OperatorContextState
/pm:OperatorDetails
/pm:Title
|

|OBR-10/XCN-9
|Assigning Authority
|pm:OperatorContextState
/pm:Identification
| HL7 data type *HD*

|OBR-10/XCN-9.1
|Namespace ID
|/@Root
|The @Root contains the unique identification of the HDO.

*Note that if the HDO identifer is not defined the XCN-9 field shall be left empty.*

|===

===== OBX - Observation/Result Segment
The the HL7 Obervation/Result (OBX) segment requires a mapping from the SDC containment tree and metric items to the OBX segment fields.

More information about the containment tree mapping can be found in *Appendix A Mapping ISO/IEEE 11073 Domain Information Model to HL7* in the <<ihe_pcd_tf-2_2019>>

====== OBX-2 Value Type
The OBX-2 field shall be set to the metric value type code as define in *HL7 table 0125*. The table <<ref_tbl_dec_obx2_mapping>> defines the mapping of the SDC metric type to the data fields of the HL7 data type *ID* used in the OBX-2 field.

[NOTE]
This field shall be left empty for OBX segments defining the device's MDS, VMD, or CHAN containment tree elements.

[#ref_tbl_dec_obx2_mapping]
.OBX-2 Value Type Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|OBX-2/ID-1
|Coded Value for HL7-Defined Tables
|*"NM"* if the metric state is of type *pm:NumericMetricState*.

*"ST"* if the metric state is of type *pm:StringMetricState*.

*"CWE"* if the metric state is of type *pm:EnumStringMetricState*.

|

|===

====== OBX-3 Observation Identifier
The OBX-3 field shall contain the identifier of the element in the hierarchical containment tree such as MDS, VMD, CHAN, or the actual related metric to be exported. The tables below defines the mapping of the SDC containment tree element to the data fields of the HL7 data type *CWE* used in the OBX-3 field.

[NOTE]
====
If a private *MDC* code is used for the coding of the SDC containment tree element, the identifier shall be mapped as described in section <<ref_private_coding_system_note>>.
====

[#ref_tbl_dec_obx3_mds_mapping]
.OBX-3 Observation Identifier Mapping - MDS Level
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|OBX-3/CWE-1
|Identifier
|pm:Mds
/pm:Type
/@Code
|

|OBX-3/CWE-2
|Text
|If *@Code* is an MDC code, this field shall contain the RefId of the MDC code.

In all other cases, the field shall be set to the pm:Mds /pm:Type /@SymbolicCodeName.
| Note that MDC is the default coding system if no coding system is specified.

|OBX-3/CWE-3
|Name of Coding System
|*"MDC"* if no other coding system is specified.

In all other cases, the field shall be set to pm:Mds /pm:Type /@CodingSystem.

|Note that MDC is the default coding system if no coding system is specified.

|===

[#ref_tbl_dec_obx3_vmd_mapping]
.OBX-3 Observation Identifier Mapping - VMD Level
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|OBX-3/CWE-1
|Identifier
|pm:Vmd
/pm:Type
/@Code
|

|OBX-3/CWE-2
|Text
|If *@Code* is an MDC code, this field shall contain the RefId of the MDC code.

In all other cases, the field shall be set to the pm:Vmd /pm:Type /@SymbolicCodeName.
| Note that MDC is the default coding system if no coding system is specified.

|OBX-3/CWE-3
|Name of Coding System
|*"MDC"* if no other coding system is specified.

In all other cases, the field shall be set to pm:Vmd /pm:Type /@CodingSystem.

|Note that MDC is the default coding system if no coding system is specified.

|===

[#ref_tbl_dec_obx3_chan_mapping]
.OBX-3 Observation Identifier Mapping - CHAN Level
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|OBX-3/CWE-1
|Identifier
|pm:Channel
/pm:Type
/@Code
|

|OBX-3/CWE-2
|Text
|If *@Code* is an MDC code, this field shall contain the RefId of the MDC code.

In all other cases, the field shall be set to the pm:Channel /pm:Type /@SymbolicCodeName.
| Note that MDC is the default coding system if no coding system is specified.

|OBX-3/CWE-3
|Name of Coding System
|*"MDC"* if no other coding system is specified.

In all other cases, the field shall be set to pm:Channel /pm:Type /@CodingSystem.

|Note that MDC is the default coding system if no coding system is specified.

|===

[#ref_tbl_dec_obx3_metric_mapping]
.OBX-3 Observation Identifier Mapping - Metric Level
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|OBX-3/CWE-1
|Identifier
|pm:NumericMetricDescriptor
/pm:Type
/@Code

pm:StringMetricDescriptor
/pm:Type
/@Code

pm:EnumStringMetricDescriptor
/pm:Type
/@Code
|

|OBX-3/CWE-2
|Text
|If *@Code* is an MDC code, this field shall contain the RefId of the MDC code.

In all other cases, the field shall be set to the pm:xxxMetricDescriptor /pm:Type /@SymbolicCodeName.
|Note that MDC is the default coding system if no coding system is specified.

|OBX-3/CWE-3
|Name of Coding System
|*"MDC"* if no other coding system is specified.

In all other cases, the field shall be set to pm:xxxMetricDescriptor /pm:Type /@CodingSystem.

|Note that MDC is the default coding system if no coding system is specified.

|===


[#ref_dec_obx4]
====== OBX-4 Observation Sub-ID
The OBX-4 field shall contain a flattened representation of the SDC element in the hierarchical containment tree. Please refer to the IHE technical framework <<ihe_pcd_tf-2_2019>> for further information.

The gateway shall assign the handles (which are required to be unique in the same MDIB) of the containment tree elements pm:Mds, pm:Vmd, pm:Channel, and pm:Metic to unique integer numbers. The numbers have to be unique per contrainment tree level e. g. all pm:Vmd elements are assigned to a unique number. The pm:Channel elements may use the same numbers as the pm:Vmd elements but on the pm:Channel level the numbers must be unique as well.

There is no requirement to preserve the same assigned number for a containment tree element from message to message, but it is highly recommended since this makes it much easier for the DOC to process the HL7 V2 messages.

.Containment Tree Element Handle Assignment
====
The gateway assigns the handles of the containment tree elements to

* "3" for pm:Mds/@Handle="My1Mds".
* "1" for pm:Vmd/@Handle="Vmd.1".
* "2" for pm:Channel/@Handle="Chan.4".
* "1" for pm:Metric/@Handle="Metric.Spo2".

The OBX-4 field for the containment tree elements shall be set to

* "3.0.0.0" for the MDS OBX segment.
* "3.1.0.0" for the VMD OBX segment.
* "3.1.2.0" for the CHAN OBX segment.
* "3.1.2.1" for the Metric OBX segment.
====

