===== MSH - Message Header Segment
The HL7 Message Header (MSH) segment requires a mapping between the SDC MDIB content and the MSH segment fields.

If not differently specified in this section, the MSH segment fields shall be in compliance with the [PCD-01] (DEC gateway) or [PCD-04] (ACM gateway) transaction, retrospectively, as described in the <<ihe_pcd_tf-2_2019>>.

[NOTE]
====
If the SDC MDIB contains several MDS elements that could operate in different *pm:MdsState/@OperatingMode* states, there shall be a separate [PCD-01] message per MDS.
====

====== MSH-11 Processing ID
The MSH-11 field shall contain the code for the processing ID which shall either be *"P"* (Production) or *"D"* (Debugging). The table <<ref_tbl_msh11_mapping>> defines the mapping of the SDC MDS information to the data fields of the HL7 data type *PT* used in the MSH-11 field.

[#ref_tbl_msh11_mapping]
.MSH-11 Processing ID Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|MSH-11/PT-1
|Processing ID
|pm:MdsState
/@OperatingMode
|Note that the HL7 Processing ID value set (HL7 table 0103) differs from the SDC pm:MdsOperatingMode value set and requires a mapping accordingly (see also <<ref_tbl_mdsopmode_mapping>>).

|===

[#ref_tbl_mdsopmode_mapping]
.pm:mdsOperatingMode to Processing ID Value Set Mapping
|===
|SDC Value |SDC Description |HL7 Value |HL7 Description

|Nml
|Nml = Normal
|P
|Production

|Dmo

Srv

Mtn
|Dmo = Demo

Srv = Service

Mtn = Maintenance
|D
|Debugging

|===