include::tf2-ch-b-gateway-global-vars.adoc[]

= SDPi ACM Gateway -- Mapping

NOTE:  This file contains the SDPi gateway actor (SOMDS_ACM_Gateway) logic for mapping from SDC BICEPS MDIB content and interactions with IHE DEV "PCD" ACM profile messaging.

== Scope
This chapter defines the mapping from SDC MDIB content as defined in this document and its underlying standards, to IHE Alert Communication Management (ACM) profile messages as defined in the *{var_ihe_tf-2_long}*.

The SDPi gateway actor represents the Alarm Reporter (AR) role of the IHE ACM profile.

The following sections supplement the IHE ACM profile as appropriate. If there are no supplementing definitions, the definitions as described in the *{var_ihe_tf-2_short}* will apply.

== Referenced Standards & Profiles
This section provides an overview about the referenced standards and profiles used in this chapter:

* {var_ihe_tf-2_long}
* {var_sdc_std_10207}
* {var_sdc_std_10700}
* {var_sdc_std_10701}
* {var_sdc_std_10702}

== HL7 Segment Descriptions
The following sections refer to the *Appendix B Common Segment Descriptions* of the *{var_ihe_tf-2_long}*.

=== MSH - Message Header Segment
The HL7 Message Header (MSH) segment does not require a specific mapping between the SDC MDIB content and the HL7 ACM profile messages. In context of this chapter, the MSH segment content shall be in compliance with the [PCD-04] transaction as described in the {var_ihe_tf-2_short}.

include::tf2-ch-b-gateway-pid-mapping.adoc[]

include::tf2-ch-b-gateway-pv1-mapping.adoc[]

=== OBR - Observation Request Segment
The the HL7 Obervation Request (OBR) segment requires a mapping from the SDC containment tree and metric data to the OBR segment fields.

==== OBR-2 Placer Order Number
For IHE ACM profile, the OBR-2 field shall contain the identifier of the Alarm Reporter (AR) of the IHE ACM gateway (not the individual device identifier). For further information, please refer to the *{var_ihe_tf-2_short}*.

==== OBR-3 Filler Order Number
For the IHE ACM profile, the OBR-3 field shall contain the identifier of the Alarm Reporter (AR) of the IHE ACM gateway (not the individual device identifier). For further information, please refer to the *{var_ihe_tf-2_short}*.