===== PID - Patient Identification Segment
The HL7 Patient Identification (PID) segment requires a mapping from the SDC patient context information to the PID segment fields.

====== Prerequisite of Valid Patient Context
.R8102
[sdpi_requirement#r8102,sdpi_req_level=shall]
****
The SDC patient context information shall only be mapped to the corresponding fields in the HL7 PID segment when the requirements (e. g. inferred patient ensemble context, associated patient context, etc.) as defined in the <<ieee_11073_10700_2022>> are fulfilled.

If the SDC patient context information shall not be used for the mapping, please refer to the <<ihe_pcd_tf-2_2019>> on how to populate the fields of the PID segment in this case.
****

====== PID-3 Patient Identifier List
.R8103
[sdpi_requirement#r8103,sdpi_req_level=shall]
****
A <<actor_somds_dec_gateway>> shall map the patient identifier to the PID-3 field which is a list of patient identifiers (e. g. medical record number, socal security number, visit number, account number, etc.).

.Notes
[%collapsible]
====
NOTE: <<ref_tbl_pid3_mapping>> defines the mapping of the SDC patient identifier to the data fields of the HL7 data type *CX* used in the PID-3 field.

NOTE: The SDC patient identifier element *pm:PatientContextState/pm:Identification* may contain more than one patient identifier. Each SDC patient identifier shall be mapped according to the <<ref_tbl_pid3_mapping>> table and added to the PID-3 patient identifier list.
====
****

[#ref_tbl_pid3_mapping]
.PID-3 Patient Identifier List Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PID-3/CX-1
|ID Number
|pm:PatientContextState
/pm:Identification
/@Extension
|The @Extension attribute contains the unique patient identifer.

*Note that the field may contain a null value indicating that the identifier is missing.*

|PID-3/CX-4
|Assigning Authority
|pm:PatientContextState
/pm:Identification
| HL7 data type *HD*

|PID-3/CX-4.1
|Namespace ID
|/@Root
|The @Root contains the unique identification of the HDO.

*Note that if the HDO identifer is not defined the CX-4 field shall be left empty.*

|PID-3/CX-5
|Identifier Type Code
|pm:PatientContextState
/pm:Identification
/pm:Type
/@Code
|The type of the patient identifier set in the @Code attribute shall be set to a value from HL7 V2 table 0203. The @CodingSystem shall be set to *"urn:oid:2.16.840.1.113883.18.108"*.

|===

The following identifier type codes are proposed to be used for the patient identifier in the point of care device:

[#ref_tbl_pid5_itc_valueset]
.Patient Identifier Type Code Value Set
|===
|Value |Description

|AN
|Account Number

|MR
|Medical Record Number

|PI
|Patient Internal Identifier

|U
|Unspecified Identifier

|VN
|Visit Number

|===

====== PID-5 Patient Name
.R8104
[sdpi_requirement#r8104,sdpi_req_level=shall]
****
A <<actor_somds_dec_gateway>> shall set the PID-5 field to the patient name information.

.Notes
[%collapsible]
====
NOTE: <<ref_tbl_pid5_mapping>> defines the mapping of the SDC patient name information to the data fields of the HL7 data type *XPN* used in the PID-5 field.
====
****

[#ref_tbl_pid5_mapping]
.PID-5 Patient Name Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PID-5/XPN-1
|Family Name
|pm:PatientContextState
/pm:CoreData
|HL7 data type *FN*

|PID-5/XPN-1.1
|Surname
|/pm:Familyname
|

|PID-5/XPN-2
|Given Name
|pm:PatientContextState
/pm:CoreData
/pm:Givenname
|

|PID-5/XPN-3
|Second and Further Given Names or Initials
|pm:PatientContextState
/pm:CoreData
/pm:Middlename
|

|PID-5/XPN-5
|Prefix (e.g. DR)
|pm:PatientContextState
/pm:CoreData
/pm:Title
|

|PID-5/XPN-7
|Name Type Code
|pm:PatientContextState
/pm:CoreData
|This field shall be set to "L" when a patient name is available, or "U" when the patient name is not set.

Please refer also to the corresponding section in the <<ihe_pcd_tf-2_2019>>.

|===

====== PID-6 Mother’s Maiden Name
.R8105
[sdpi_requirement#r8105,sdpi_req_level=shall]
****
A <<actor_somds_dec_gateway>> shall set the PID-6 field to the mother's maiden name or birth name before marriage.

.Notes
[%collapsible]
====
NOTE: <<ref_tbl_pid6_mapping>> defines the mapping of the SDC patient name information to the data fields of the HL7 data type *XPN* used in the PID-6 field.
====
****

[#ref_tbl_pid6_mapping]
.PID-6 Mother’s Maiden Name Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PID-6/XPN-1
|Family Name
|pm:PatientContextState
/pm:CoreData
|HL7 data type *FN*

|PID-6/XPN-1.1
|Surname
|/pm:Birthname
|

|===

====== PID-7 Date/Time of Birth
.R8106
[sdpi_requirement#r8106,sdpi_req_level=shall]
****
A <<actor_somds_dec_gateway>> shall set the PID-7 field to the date & time of birth.

.Notes
[%collapsible]
====
NOTE: <<ref_tbl_pid7_mapping>> defines the mapping of the SDC patient's date of birth information to the data fields of the HL7 data type *DTM* used in the PID-7 field.
====
****

[#ref_tbl_pid7_mapping]
.PID-7 Date/Time of Birth Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PID-6/DTM-1
|Date/Time
|pm:PatientContextState
/pm:CoreData
/pm:DateOfBirth
|Note that the HL7 date & time format differs from the xsd date/time formats and requires a mapping accordingly (see also <<ref_expl_dt_mapping>>).

|===

[#ref_expl_dt_mapping]
.Date/Time Format Mapping
====
xsd:dateTime: *2001-10-26T21:32:52* -> HL7 DTM: *20011026213252*

xsd:date: *2001-10-26* -> HL7 DTM: *20011026*
====

====== PID-8 Administrative Sex
.R8107
[sdpi_requirement#r8107,sdpi_req_level=shall]
****
A <<actor_somds_dec_gateway>> shall set the PID-8 field to the code for the administrative sex.

However, in the clinical context of a point of care device the biological sex, or sex at birth is important for various algorithms.

.Notes
[%collapsible]
====
NOTE: <<ref_tbl_pid8_mapping>> defines the mapping of the SDC patient's sex information to the data fields of the HL7 data type *IS* used in the PID-8 field.
====
****

[NOTE]
====
The sex and gender of a patient (or a newborn) cannot exactly be mapped from ISO/IEEE 11073-10207 to HL7 V2. The domain information and service model only contains an attribute for sex as defined by biological and physiological characteristics. HL7 V2, on the other hand, only provides a field for the administrative sex as defined by the socially constructed roles, behaviours, activities, and attributes that a given society considers appropriate. The biological sex, however, does not necessarily match a person’s administrative gender. Mapping from one to the other would therefore introduce errors. However, in the clinical context of a point of care device the biological sex, or sex at birth is important for various algorithms, and therefore, shall be mapped to the PID-8 field.
====

[#ref_tbl_pid8_mapping]
.PID-8 Administrative Sex Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PID-8/IS-1
|Administrative Sex
|pm:PatientContextState
/pm:CoreData
/pm:Sex
|Note that the HL7 Administrative Sex value set (HL7 table 0001) differs from the SDC pm:Sex value set and requires a mapping accordingly (see also <<ref_tbl_sex_mapping>>).

|===

[#ref_tbl_sex_mapping]
.Patient's Sex Value Set Mapping
|===
|SDC Value |SDC Description |HL7 Value |HL7 Description

|Unspec
|Unspecified. Sex is not designated.
|A
|Ambiguous

|M
|Male. Indicates a male patient.
|M
|Male

|F
|Female. Indicates a female patient.
|F
|Female

|Unkn
|Unknown. Indicates that the sex is unknown for different reasons.
|U
|Unknown

|===

// https://build.fhir.org/ig/HL7/uv-pocd/StructureDefinition-Patient.html

====== PID-10 Race
.R8108
[sdpi_requirement#r8108,sdpi_req_level=shall]
****
A <<actor_somds_dec_gateway>> shall set the PID-10 field to the patient's race.

.Notes
[%collapsible]
====
NOTE: <<ref_tbl_pid10_mapping>> defines the mapping of the SDC patient's race information to the data fields of the HL7 data type *CWE* used in the PID-10 field.
====
****

[#ref_tbl_pid10_mapping]
.PID-10 Race Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PID-10/CWE-1
|Identifier
|pm:PatientContextState
/pm:CoreData
/pm:Race
/@Code
|

|PID-10/CWE-2
|Text
|pm:PatientContextState
/pm:CoreData
/pm:Race
/@SymbolicCodeName
|

|PID-10/CWE-3
|Name of Coding System
|pm:PatientContextState
/pm:CoreData
/pm:Race
/@CodingSystem
|

|PID-10/CWE-4
|Alternate Identifier
|pm:PatientContextState
/pm:CoreData
/pm:Race
/pm:Translation
/@Code
|Note that only the first entry of the *pm:Translation* element list shall be mapped.

|PID-10/CWE-6
|Name of Alternate Coding System
|pm:PatientContextState
/pm:CoreData
/pm:Race
/pm:Translation
/@CodingSystem
|Note that only the first entry of the *pm:Translation* element list shall be mapped.

|PID-10/CWE-7
|Coding System Version ID
|pm:PatientContextState
/pm:CoreData
/pm:Race
/@CodingSystemVersion
|

|PID-10/CWE-8
|Alternate Coding System Version ID
|pm:PatientContextState
/pm:CoreData
/pm:Race
/pm:Translation
/@CodingSystemVersion
|Note that only the first entry of the *pm:Translation* element list shall be mapped.

|===

====== PID-31 Identity Unknown Indicator
.R8109
[sdpi_requirement#r8109,sdpi_req_level=shall]
****
A <<actor_somds_dec_gateway>> shall set the PID-31 field to an indicator whether or not the patient's identity is known.
****

The field value shall be determined from the present of a patient-inferred ensemble context (*pm:EnsembleContextDescriptor/pm:Type/@Code = MDC_IDT_ENSEMBLE_PATIENT_INFERRED*) with an associated context association state (*pm:EnsembleContextState/@ContextAssociation = Assoc*). In this case, the value shall be set to "Y".

In all other cases, the value shall be set to "N".

====== PID-33 Last Update Date/Time
.R8110
[sdpi_requirement#r8110,sdpi_req_level=shall]
****
A <<actor_somds_dec_gateway>> shall set the PID-33 field to the date & time of last patient context update.

.Notes
[%collapsible]
====
NOTE: <<ref_tbl_pid33_mapping>> defines the mapping of the SDC patient context update information to the data fields of the HL7 data type *DTM* used in the PID-33 field.

NOTE: The SDC data model does not support the concept of a last update timestamp. The SDC consumer participant could determine context updates from the SDC state report events (receiving timestamp of the state report). However, when the connection between the SDC provider and SDC consumer gets lost, the SDC consumer will not be able to determine the lastest update timestamp.
====
****

[#ref_tbl_pid33_mapping]
.PID-33 Last Update Date/Time Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PID-33/DTM-1
|Date/Time
|If *pm:PatientContextState
/pm:Identification
/@ContextAssociation = Assoc*, the field shall be set to *pm:PatientContextState/@BindingStartTime*.

In all other cases, the field shall be set to *pm:PatientContextState/@BindingEndTime*.

|Note that the HL7 date & time format differs from the xsd date/time formats and requires a mapping accordingly (see also <<ref_expl_dt_mapping>>).

|===