
// = Open Issues and Questions

#FOR A FORMAT EXAMPLE SEE https://profiles.ihe.net/ITI/BALP/issues.html#

[sdpi_offset=clear]
=== SDPi "Topic of Interest" Issue Management

#PROVIDE AN OVERVIEW OF HOW SDPI ISSUES ToI are managed and lined below; include a reference to the wiki article on co-working#

All SDPi supplement issues are tracked in the https://github.com/IHE/sdpi-fhir/issues[IHE Github sdpi-fhir repository Issues section]. Filter the issues on "SDPi Topic of Interest" to see a full list.  +

* To see the full list of OPEN issues, filter on: is:issue is:open label:"SDPi Topic of Interest"
* To see the full list of CLOSED issues, filter on: is:issue is:closed label:"SDPi Topic of Interest"


[sdpi_offset=clear]
=== Open Issues and Questions

* *Issue:* https://confluence.hl7.org/pages/viewpage.action?pageId=86970701[*SystemContext Profiling & Use*]
** How should SDPi profile(s) use the SDC SystemContext (Location, Patient, Ensemble, Workflow) capabilities?  Including device pairing / coupling.  Which SystemContext component?  Is this an option on the SDPi-P profile?  Other profiles?  IEEE 11073-1070x PKP requirements?

* *Issue:* *_MDIB Version Update Guidelines_*
** SDC provides "version" indicators to enable CONSUMER systems to determine what has changed.  However, this can result in considerable "chatter" on the network if not properly managed.  What guidelines and requirements should be specified in SDPi-P?  Also how managed with waveforms vs. parameters.

* *Issue:* *_Profiling BICEPS Services in SDPi-P_*
** SDC/BICEPS provides a general service model that supports many implementation approaches.  How should the services be utilized in SDPi-Plug-n-trust 1.0?

* *Issue:* https://confluence.hl7.org/pages/viewpage.action?pageId=91994093[*_Security Certificate Provisioning_*]
** ISO/IEEE 11073-20702 MDPWS defines how WS-Security w/ X.509 certificates and Extended Key Use (EKU) provisions should be adapted for SDC; however, SDPi profiles will not only add specificity, but also address operationalization challenges including security certificate provisioning.  What should be added to the SDPi supplement to support this operationalization?  What should be added to the Gemini SDPi+FHIR program, including tooling and testing, to support SDPi security?

* *Issue:* https://confluence.hl7.org/display/GP/Topic%3A+SDPi-P+Compression+Option[*_SDPi-P Compression Option_*]
** https://github.com/IHE/sdpi-fhir/issues/97[Github Issue #97 _Append TOI: Compression Option_] +
##ADDED A NOTE TO THE ISSUE THAT THIS IS STILL OPEN IN THE ToI TABLE AND THUS IN THE OPEN LIST THOUGH IT HAS A GITHUB ISSUE NUMBER
##
** MDPWS defines EXI as the designated means to compress XML data. Unluckily, even though EXI is a W3C recommendation since 2014 it hasn't been widely adopted. Another means to compress data of any type is HTTP 1.1 content encoding, build-in to most HTTP servers. What should SDPi-P require for the compression option?

* *Issue:* https://confluence.hl7.org/pages/viewpage.action?pageId=104761310[*_MDIB Report Retrofit / Best Practices_*]
** https://github.com/IHE/sdpi-fhir/issues/104[Github Issue \#104 _Append TOI: MDIB Report Retrofit / Best Practices_] +
##ADDED A NOTE TO THE ISSUE THAT THIS IS STILL OPEN IN THE ToI TABLE AND THUS IN THE OPEN LIST THOUGH IT HAS A GITHUB ISSUE NUMBER
##
** MDIB reports are sent out every time descriptors or states of an MDIB containment tree change. Descriptor changes cause corresponding states to also change whereas state changes do not cause descriptors to change. A BICEPS Service Provider is supposed to transmit every change of descriptors and their corresponding states in various of the report and and streams. Unfortunately, BICEPS lacks requirements when it comes to the generation of report messages to the extent that BICEPS Service Consumers cannot appropriately be implemented at reasonable costs. This topic of interest discusses best practices for the transmission of MDIB reports in a way that BICEPS Service Consumers can effectively and efficiently process those reports.

* *Issue:* *_BICEPS Extension Model Use in SDPi?_*
** SDC provides for extensions, especially in BICEPS.  How should these be included and utilized in SDPi?  A key issue to avoid is the infamous HL7 V2 "Z" segment, which was over used and negatively impacted interoperability.

* *Issue:* https://confluence.hl7.org/display/GP/Topic%3A+Discovery+Proxy+Actors[*_Discovery Proxy Actors_*]
** Note: _This issue is targeted for v1.1 but may have some element in v1.0_
** ISO/IEEE 11073 SDC provides for both implicit and explicit discovery; however, for some implementations this may result in unwanted message traffic across the network; the use of a "discovery proxy" has been proposed and could be added as an optional SDPi actor.

[sdpi_offset=clear]
=== Closed Issues

* *Issue: _Connect Time Delay Algorithm_*
** https://github.com/IHE/sdpi-fhir/issues/103[Github Issue #103 _Append TOI: Connect Time Delay Algorithm_] +
https://github.com/IHE/sdpi-fhir/issues/33[Github Issue #33 _Topic: Connect Time Delay Algorithm_] +
##IS ONE OF THE ABOVE ISSUES STALE?##
** #Identify list of updates to this supplement w/ links#

* *Issue: _Handling missed discovery messages_*
** https://github.com/IHE/sdpi-fhir/issues/96[Github Issue #96 _Append TOI: Handling missed discovery messages_]
** #Identify list of updates to this supplement w/ links#

* *Issue: _Info exchanged during unsecured discovery_*
** https://github.com/IHE/sdpi-fhir/issues/102[Github Issue #102 _Append TOI: Info exchanged during unsecured discovery_]
** #Identify list of updates to this supplement w/ links#

* *Issue: _What is a Central?_*
** https://github.com/IHE/sdpi-fhir/issues/123[Github Issue #123 _Append TOI: What is a Central?_]
** #Identify list of updates to this supplement w/ links#

* *Issue: _What is a Smart Alert System?_*
** https://github.com/IHE/sdpi-fhir/issues/124[Github Issue #124 _Append TOI: What is a Smart Alert System?_]
** #Identify list of updates to this supplement w/ links#

* *Issue: _SDPi BICEPS Extension Namespace_*
** https://github.com/IHE/sdpi-fhir/issues/125[Github Issue #125 _Append TOI: SDPi BICEPS Extension Namespace_]
** #Identify list of updates to this supplement w/ links#

* *Issue: _MDIB/MDS Modeling for Device Aggregators_*
** https://github.com/IHE/sdpi-fhir/issues/126[Github Issue #126 _Append TOI: MDIB/MDS Modeling for Device Aggregators_]
** #Identify list of updates to this supplement w/ links#

* *Issue: _SDPi-xC with Mixed Device Safety Classes_*
** https://github.com/IHE/sdpi-fhir/issues/61[Github Issue #61 _Topic: SDPi-xC with Mixed Device Safety Classes_]
** #Identify list of updates to this supplement w/ links#





