
// = Introduction to this Supplement

[sdpi_offset=clear]
== Introduction to this Supplement

[%noheader]
[%autowidth]
[cols="1a"]
|===
|Whenever possible, IHE profiles are based on established and stable underlying standards. However, if an IHE domain determines that an emerging standard has high likelihood of industry adoption, and the standard offers significant benefits for the use cases it is attempting to address, the domain may develop IHE profiles based on such a standard. During Trial Implementation, the IHE domain will update and republish the IHE profile as the underlying standard evolves.

Product implementations and site deployments may need to be updated in order for them to remain interoperable and conformant with an updated IHE profile.

This <profile acronym> Profile (or This Technical Framework Supplement) is based on Release 4 of the emerging HL7^®^{empty}footnote:[HL7 is the registered trademark of Health Level Seven International.]  FHIR^®^{empty}footnote:[FHIR is the registered trademark of Health Level Seven International.]  specification. HL7 describes FHIR Change Management and Versioning at https://www.hl7.org/fhir/versions.html.

HL7 provides a rating of the maturity of FHIR content based on the FHIR Maturity Model (FMM): level 0 (draft) through N (Normative). See http://hl7.org/fhir/versions.html#maturity.

The FMM levels for FHIR content used in this profile are:

[%header]
[width=50%]
[cols="^2,^1"]
!====
.^! FHIR Content +
(Resources, ValueSets, etc.) !FMM Level

!  !

!  !

! <e.g., Communication ! 2>

!====
{empty} +

|===

{empty} +

// Reviewers notes for SDPI 1.0 DEV Internal release, indicating the focus and general conventions used for content that is in process and to be "cleaned up" by Public Release


[%noheader]
[%autowidth]
[cols="1"]
|===
a| *SDPi 1.0 Supplement -- _DEV-Internal Review Version_ -- Note*:

This release of the SDPi 1.0 supplement is intended for *IHE Devices "internal" review*, with a focus on technical content.
It is recognized that there are editorial issues that need to be resolved before the Public Comment version is released.  Known issues with this DEV Internal Review version include:

. The content is scoped per the SDPi 1.0 Capabilities specification (see https://github.com/IHE/sdpi-fhir/wiki/SDPi-Editorial-Planning-and-Versions#sdpi-version-10-detail-[wiki article "SDPi Version 1.0 (Detail)"]), though future capabilities may be included in a Reviewer Note; development of SDPi 1.x and beyond will begin early in 2023 DURING the 1.0 review periods;
. Supplement organization is based on the IHE Supplement Template from 2020; recently a newer template has been released but is not factored into this version of the supplement; also, the section allocation and organization anticipates the IHE PCD 2019 (see <<vol1_appendix_b_references>>) being updated into an IHE DEV 202x version that also conforms to the updated IHE Techncial Feramework template(s);
. This supplement includes (4) SDPi profiles; however, the general IHE Supplement Template is organized for a single profile; as a result, some adjustments have been made, especially in the supplement overview section where there is a general SDPi overview and then basic overviews for each of the profiles; challenging areas include profile "options" where there are FOUR sections vs. one; it is a work in progress and feedback is appreciated, especially for clarity;
. Figure & Table numbering needs to be fixed per IHE TF style guide conventions (e.g., section-specific numbering, for example:  Figure x.y.z-2);
. #TODO:# notes may be included; these will be removed and addressed BEFORE the Public Comment version is published;
. Technical content in TF-2 Transactions is complete; however, TF-1 and TF-3 though technically complete for 1.0 features, will require additional EDITORIAL content; limited content is provided in this DEV internal review draft, BUT guidance on what needs to be added for the Public Comment version vs. in the 1.x version should be identified;
. Requirements boxes (e.g., "R1234") have been added especially in TF-2 and some in TF-3; this is an initial approach that will be greatly expanded in future versions of the supplement; a more robust, expanded approach is provided in <<vol1_clause_sdpi_requirements_modeling_integration>>;
. This supplement is curently rendered as a *"long form"* document -- one single HTML file; however, in subsequent versions the intent is to consider a multi-page / file HTML rendering + addition of a tabbed menu for navigating the sections of the supplement;
. *FOR THE PUBLIC COMMENT* version of the supplement, it is intended to migrate the current content in the sdpi-fhir Github repository to a new DEV.SDPi repository, in alignment with current IHE conventions; major / minor version tagging, issue and pull-requiest management, etc. will be managed in that new repository. *REVIEWER COMMENTS* for this Devices-Internal review version will be tracked as Issues in the current sdpi-fhir repository.

*"SDPi 1.0 Supplement Note"* boxes are provided throughout the document to help guide reviewers and to ask specific questions for feedback requested by the supplement editors.

*REVIEWER FOCUS*:  Please review the document especially with a technical and general organizational focus.
Does the information flow logically and sufficiently for adoptors and implementers?
Is the text clear and sufficient or do specific subject areas need to be expanded or reworked.
Do the links work and lead to the right "best" destinations?  Focus on *_what must be addressed BEFORE Public Comment publication_*, recognizing that supplement development with 1.x and beyond will begin January 1st.

|===

=== SDPi Supplement Overview

This IHE Devices Technical Framework supplement introduces a new _family of interoperability profiles_, Service-oriented Device Point-of-care Interoperability (SDPi), that comprise (4) separate profiles:

* SDPi-Plug-and-trust (*SDPi-P*) Profile
* SDPi-Reporting (*SDPi-R*) Profile
* SDPi-Alerting (*SDPi-A*) Profile
* SDPi-external Control (*SDPi-xC*) Profile

To that end, the supplement includes updates to all (3) IHE DEV TF volumes, including:

*TF-1  Integration Profiles*

* General overview of the SDPi architectural approach & integrated set of profiles
* Profile specific sections
* Related appendices, for example the integration of this family of SDPi profiles with other sources of requirements - use cases or reference standards

*TF-2  Transactions*

* Extensive new set of transactions based on ISO/IEEE 11073 Service-oriented Device Connectivity (SDC) medical device interoperability standards.
* Related appendices, for example the specialized use of web services messaging for device communication and gateways to other protocols or profiles

*TF-3  Content Modules*

* New content covering the application of ISO/IEEE 11073 SDC semantic standards to device content modules, with a primary focus on specifications related to the ISO/IEEE 11073-10207 BICEPS standard.

{empty} +

=== Joint IHE-HL7 Gemini SES+MDI Project Development

#TODO:  Add an overview section here that discusses how this supplement was developed as part of the Gemini program.#

=== Supplement Support for RI+MC+RR using AsciiDoc

#TODO: Provide a high-level overview of the unique aspects of this supplement that utilizes AsciiDoc + how it supports rich metadata for implementing RI+MC+RR capabilities.  This supplement introductory section is about HOW the supplement was crafted and generally about the content vs. the actual supplement content itself which is in the Volume 1 to 3 sections.#

