skinparam monochrome true
autonumber

!global $str_sdpi_p_somds_cons = "SOMDS Consumer"
!global $str_sdpi_p_somds_prov = "SOMDS Provider"

participant "$str_sdpi_p_somds_cons" as sdpi_somds_consumer
participant "$str_sdpi_p_somds_prov" as sdpi_somds_provider

== SDPi [DEV-28]  Notify Change in System Context and Capabilities ==
|||
group secured
        |||
        note over sdpi_somds_provider, sdpi_somds_consumer
        Consider TF-2 Transactions based on BICEPS "msg:"abstract definitions,
        SOMDA "Glue" speifications, or MDPWS specifications.  
        TF-2 Appendix will have MDPWS / sdc11073 API specifications.
        end note
        |||
        alt Subscription active
                loop
                        sdpi_somds_consumer <- sdpi_somds_provider: BICEPS: DesciptionModificationReport(... [incl. states])
                end 
        |||
        else Subscription inactive
                sdpi_somds_consumer -> sdpi_somds_provider: BICEPS: GetContextStates(...)
                sdpi_somds_consumer <-- sdpi_somds_provider:  BICEPS: GetContextStatesResponse(...)
        end

end
|||



