skinparam monochrome true
autonumber

!global $str_sdpi_p_somds_cons = "SOMDS Consumer"
!global $str_sdpi_p_somds_prov = "SOMDS Provider"

participant "$str_sdpi_p_somds_cons" as sdpi_somds_consumer
participant "$str_sdpi_p_somds_prov" as sdpi_somds_provider

== SDPi [DEV-29]  Publish BICEPS Update Reports ==
|||
group secured
    note over sdpi_somds_consumer, sdpi_somds_provider:  See DEV-27 for Subscription Management
    loop while subscription is running and reports ensue
        sdpi_somds_consumer <- sdpi_somds_provider: SDC: Notification(Payload)
        sdpi_somds_consumer <- sdpi_somds_consumer: Buffer & Apply Payload on Proxy MDIB
    end
end
|||



