@startuml

'!include ../_sequence_config.incl  MAY UPDATE THIS IN A FUTURE DRAFT

'NOTE:  This file puts ALL the transaction message models into a SINGLE PNG ... FWIW :-) 

!include SDPi DEV-23.puml 
!include SDPi DEV-24.puml 
!include SDPi DEV-25.puml
!include SDPi DEV-26.puml
!include SDPi DEV-27.puml
!include SDPi DEV-28.puml
!include SDPi DEV-29.puml
!include SDPi DEV-30.puml
!include SDPi DEV-31.puml
!include SDPi DEV-32.puml
!include SDPi DEV-33.puml
!include SDPi DEV-34.puml 

@enduml