skinparam monochrome true
autonumber

!global $str_sdpi_p_somds_cons = "SOMDS Consumer"
!global $str_sdpi_p_somds_prov = "SOMDS Provider"

participant "$str_sdpi_p_somds_cons" as sdpi_somds_consumer
participant "$str_sdpi_p_somds_prov" as sdpi_somds_provider

== SDPi [DEV-32]  Retrieve Archive Data ==
|||
note over sdpi_somds_provider, sdpi_somds_consumer 
This transaction is NOT intended to support data archived over SOMDS Provider
system reset or power cycling, where DescriptorRevisions (version numbers)
may be re-initialized.  TimeFrame is intended to be minutes and hours.
BUT
??? Why can't TimeFrame be used WHEN detection of VERSION sequence 
numbering discontinuity?  Then Reconcile (having retrieved with last known 
good TimeFrame/Start) ???

RESOLUTION:
(1) LOOP due to potential size limits + requesting more states than descriptors 
(2) 
end note
group secured
    sdpi_somds_consumer -> sdpi_somds_provider: SDC: GetDescriptorsFromArchive(DescriptorFilter)
    sdpi_somds_consumer <-- sdpi_somds_provider: SDC: GetDescriptorsFromArchiveResponse(ArchivedDescriptors)
    |||
    loop
        note over sdpi_somds_consumer, sdpi_somds_provider: WHAT IS THE BASIS FOR THIS LOOP?
        sdpi_somds_consumer -> sdpi_somds_provider: SDC: GetStatesFromArchive(StatesFilter)
        sdpi_somds_consumer <-- sdpi_somds_provider: SDC: GetStatesFromArchiveResponse(ArchivedStates)
    end
end
|||
