= Appendix C – Device Point-of-care Interoperability (DPI) Use Cases


NOTE:  This file integrates the use cases that are linked to the SDPi profiles to provide functional requirements, including any introductory sections for how use cases are managed in SDPi. +
{empty} +
Note that each use case is in its own file. +
{empty} +
Note that AsciiDoc Gherkin (plugin?) may be used ... eventually ... !

[appendix#vol1_appendix_c_dpi_use_cases,sdpi_offset=C]
== Appendix C - DPI Use Cases

This Appendix describes a number of use cases that explore the various SDPi functions.
Each Use Case (also called a Feature in Gherkin) is organized as follows:

•	*Narrative* – a description of the desired functionality from the user perspective
•	*Technical Pre-Conditions* – any assumptions or pre-conditions
•	*Scenario(s)* – the scenarios explore both the Happy Path when everything goes according to plan and the Alternative Paths where things do not go according to plan.

##TODO:  Include model graphic showing relationships ...
##
// C.1
[sdpi_offset=1]
=== Overview of DPI Narratives, Use Cases & Scenarios

// C.1.1
==== Rich History of Medical Device Interoperability Use Cases

// C.1.2
==== Overview of Architectural & Business Systems Concepts

// C.1.3
==== Overview of DIS & DAS Medical Device Alert Distribution Systems

// C.1.4
==== Use Case Specification Conventions Using Cucumber/Gherkin

// C.2
include::tf1-ch-c-use-case-scad.adoc[]


