name: Verify and upload SDPi supplement
    
on: [push]

env:
  CI: true
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Create TF-2 PDF with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: run --args="--input-file ../sdpi_supplement_tf_2.adoc --output-folder ../sdpi-supplement --backend pdf"
        build-root-directory: SDPi_Supplement/asciidoc-converter
        
    - name: Create TF-2 HTML with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: run --args="--input-file ../sdpi_supplement_tf_2.adoc --output-folder ../sdpi-supplement --backend html"
        build-root-directory: SDPi_Supplement/asciidoc-converter
        
    - name: Upload artifact
      if: success() && github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v3
      with:
        name: sdpi-supplement
        path: SDPi_Supplement/sdpi-supplement
