@startuml

!include ../_sequence_config.puml.incl

sdc_sc -> sdc_sp: Subscribe({DescriptionModificationReport, EpisodicAlertReport})
sdc_sc <-- sdc_sp: SubscribeResponse(SubscriptionManager, ExpirationTime)

loop while subscription is running and reports ensue
    opt
        sdc_sc <- sdc_sp: Notification(DescriptionModificationReport)
        note left: Description modifications\nalways first
    end
    
    sdc_sc <- sdc_sp: Notification(EpisodicAlertReport)
end

!include ../update_report_retrieval/update_report_retrieval__unsubscribe.puml.incl

@enduml