:var_uri_ws_eventing_notification: https://www.w3.org/Submission/2006/SUBM-WS-Eventing-20060315/#Notifications
:var_label_dev_29_message_alertreport: EpisodicAlertReport
:var_label_dev_29_message_metricreport: EpisodicMetricReport
:var_label_dev_29_message_componentreport: EpisodicComponentReport
:var_label_dev_29_message_waveformstream: WaveformStream
:var_uri_dpws_messaging: http://docs.oasis-open.org/ws-dd/dpws/1.1/os/wsdd-dpws-1.1-spec-os.html#_Toc228672084

[#vol2_clause_appendix_mdpws_dev_29]
==== MDPWS: Publish BICEPS Update Reports  [DEV-29]


// ---------- EpisodicAlertReport ---------


===== {var_label_dev_29_message_alertreport} Message

The <<vol2_clause_dev_29_message_notification, {var_label_dev_29_message_alertreport}>> message is encoded by using {var_uri_dpws_messaging}[DPWS Messaging].

====== Referenced Standards

* <<dpws_2009>> {var_uri_dpws_messaging}[Section 2 Messaging]

====== Message Outline

.EpisodicAlertReport message
[source#vol2_clause_appendix_a_mdpws_dev_29_alertreport,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-29-alertreport.xml[]
----

====== Message Semantics

`s12:Envelope/s12:Body/msg:EpisodicAlertReport`:: Updated alert information of a <<actor_somds_provider>>.

// ---------- EpisodicMetricReport ---------

===== {var_label_dev_29_message_metricreport} Message

The <<vol2_clause_dev_29_message_notification, {var_label_dev_29_message_metricreport}>> message is encoded by using {var_uri_dpws_messaging}[DPWS Messaging].

====== Referenced Standards

* <<dpws_2009>> {var_uri_dpws_messaging}[Section 2 Messaging]

====== Message Outline

.EpisodicMetricReport message
[source#vol2_clause_appendix_a_mdpws_dev_29_metricreport,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-29-metricreport.xml[]
----

====== Message Semantics

`s12:Envelope/s12:Body/msg:EpisodicMetricReport`:: Updated metric information of a <<actor_somds_provider>>.

// ---------- EpisodicComponentReport ---------

===== {var_label_dev_29_message_componentreport} Message

The <<vol2_clause_dev_29_message_notification, {var_label_dev_29_message_componentreport}>> message is encoded by using {var_uri_dpws_messaging}[DPWS Messaging].

====== Referenced Standards

* <<dpws_2009>> {var_uri_dpws_messaging}[Section 2 Messaging]

====== Message Outline

.EpisodicComponentReport message
[source#vol2_clause_appendix_a_mdpws_dev_29_componentreport,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-29-componentreport.xml[]
----

====== Message Semantics

`s12:Envelope/s12:Body/msg:EpisodicComponentReport`:: Updated component information of a <<actor_somds_provider>>.

// ---------- WaveformStream ---------

===== {var_label_dev_29_message_waveformstream} Message

The <<vol2_clause_dev_29_message_notification, {var_label_dev_29_message_waveformstream}>> message is encoded by using {var_uri_dpws_messaging}[DPWS Messaging].

====== Referenced Standards

* <<dpws_2009>> {var_uri_dpws_messaging}[Section 2 Messaging]

====== Message Outline

.WaveformStream message
[source#vol2_clause_appendix_a_mdpws_dev_29_waveformstream,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-29-waveformstream.xml[]
----

====== Message Semantics

`s12:Envelope/s12:Body/msg:WaveformStream`:: Waveform stream of a <<actor_somds_provider>>.